/*
 * This file is generated by jOOQ.
*/
package com.pingyueryou.ishare.jooq.tables;


import com.pingyueryou.ishare.jooq.Indexes;
import com.pingyueryou.ishare.jooq.Ishare;
import com.pingyueryou.ishare.jooq.Keys;
import com.pingyueryou.ishare.jooq.tables.records.IClassRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IClass extends TableImpl<IClassRecord> {

    private static final long serialVersionUID = 888043933;

    /**
     * The reference instance of <code>ishare.i_class</code>
     */
    public static final IClass I_CLASS = new IClass();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<IClassRecord> getRecordType() {
        return IClassRecord.class;
    }

    /**
     * The column <code>ishare.i_class.id</code>.
     */
    public final TableField<IClassRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>ishare.i_class.name</code>.
     */
    public final TableField<IClassRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(200).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>ishare.i_class.grade_id</code>.
     */
    public final TableField<IClassRecord, Long> GRADE_ID = createField("grade_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>ishare.i_class.order</code>.
     */
    public final TableField<IClassRecord, Integer> ORDER = createField("order", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("999999", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>ishare.i_class.created_at</code>.
     */
    public final TableField<IClassRecord, Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>ishare.i_class.updated_at</code>.
     */
    public final TableField<IClassRecord, Timestamp> UPDATED_AT = createField("updated_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>ishare.i_class</code> table reference
     */
    public IClass() {
        this(DSL.name("i_class"), null);
    }

    /**
     * Create an aliased <code>ishare.i_class</code> table reference
     */
    public IClass(String alias) {
        this(DSL.name(alias), I_CLASS);
    }

    /**
     * Create an aliased <code>ishare.i_class</code> table reference
     */
    public IClass(Name alias) {
        this(alias, I_CLASS);
    }

    private IClass(Name alias, Table<IClassRecord> aliased) {
        this(alias, aliased, null);
    }

    private IClass(Name alias, Table<IClassRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Ishare.ISHARE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.I_CLASS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<IClassRecord, Long> getIdentity() {
        return Keys.IDENTITY_I_CLASS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<IClassRecord> getPrimaryKey() {
        return Keys.KEY_I_CLASS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<IClassRecord>> getKeys() {
        return Arrays.<UniqueKey<IClassRecord>>asList(Keys.KEY_I_CLASS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IClass as(String alias) {
        return new IClass(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IClass as(Name alias) {
        return new IClass(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public IClass rename(String name) {
        return new IClass(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public IClass rename(Name name) {
        return new IClass(name, null);
    }
}
