/*
 * This file is generated by jOOQ.
*/
package com.pingyueryou.ishare.jooq.tables;


import com.pingyueryou.ishare.jooq.Indexes;
import com.pingyueryou.ishare.jooq.Ishare;
import com.pingyueryou.ishare.jooq.Keys;
import com.pingyueryou.ishare.jooq.tables.records.IIndexBannerRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IIndexBanner extends TableImpl<IIndexBannerRecord> {

    private static final long serialVersionUID = -557089224;

    /**
     * The reference instance of <code>ishare.i_index_banner</code>
     */
    public static final IIndexBanner I_INDEX_BANNER = new IIndexBanner();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<IIndexBannerRecord> getRecordType() {
        return IIndexBannerRecord.class;
    }

    /**
     * The column <code>ishare.i_index_banner.id</code>.
     */
    public final TableField<IIndexBannerRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>ishare.i_index_banner.image_url</code>.
     */
    public final TableField<IIndexBannerRecord, String> IMAGE_URL = createField("image_url", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>ishare.i_index_banner.order</code>.
     */
    public final TableField<IIndexBannerRecord, Integer> ORDER = createField("order", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("999999", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>ishare.i_index_banner.created_at</code>.
     */
    public final TableField<IIndexBannerRecord, Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>ishare.i_index_banner.updated_at</code>.
     */
    public final TableField<IIndexBannerRecord, Timestamp> UPDATED_AT = createField("updated_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>ishare.i_index_banner</code> table reference
     */
    public IIndexBanner() {
        this(DSL.name("i_index_banner"), null);
    }

    /**
     * Create an aliased <code>ishare.i_index_banner</code> table reference
     */
    public IIndexBanner(String alias) {
        this(DSL.name(alias), I_INDEX_BANNER);
    }

    /**
     * Create an aliased <code>ishare.i_index_banner</code> table reference
     */
    public IIndexBanner(Name alias) {
        this(alias, I_INDEX_BANNER);
    }

    private IIndexBanner(Name alias, Table<IIndexBannerRecord> aliased) {
        this(alias, aliased, null);
    }

    private IIndexBanner(Name alias, Table<IIndexBannerRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Ishare.ISHARE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.I_INDEX_BANNER_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<IIndexBannerRecord, Long> getIdentity() {
        return Keys.IDENTITY_I_INDEX_BANNER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<IIndexBannerRecord> getPrimaryKey() {
        return Keys.KEY_I_INDEX_BANNER_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<IIndexBannerRecord>> getKeys() {
        return Arrays.<UniqueKey<IIndexBannerRecord>>asList(Keys.KEY_I_INDEX_BANNER_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IIndexBanner as(String alias) {
        return new IIndexBanner(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IIndexBanner as(Name alias) {
        return new IIndexBanner(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public IIndexBanner rename(String name) {
        return new IIndexBanner(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public IIndexBanner rename(Name name) {
        return new IIndexBanner(name, null);
    }
}
