/*
 * This file is generated by jOOQ.
*/
package com.pingyueryou.ishare.jooq.tables;


import com.pingyueryou.ishare.jooq.Indexes;
import com.pingyueryou.ishare.jooq.Ishare;
import com.pingyueryou.ishare.jooq.Keys;
import com.pingyueryou.ishare.jooq.tables.records.IItemLendOrderRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IItemLendOrder extends TableImpl<IItemLendOrderRecord> {

    private static final long serialVersionUID = -546603192;

    /**
     * The reference instance of <code>ishare.i_item_lend_order</code>
     */
    public static final IItemLendOrder I_ITEM_LEND_ORDER = new IItemLendOrder();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<IItemLendOrderRecord> getRecordType() {
        return IItemLendOrderRecord.class;
    }

    /**
     * The column <code>ishare.i_item_lend_order.id</code>.
     */
    public final TableField<IItemLendOrderRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>ishare.i_item_lend_order.user_id</code>.
     */
    public final TableField<IItemLendOrderRecord, Long> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>ishare.i_item_lend_order.item_id</code>.
     */
    public final TableField<IItemLendOrderRecord, Long> ITEM_ID = createField("item_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>ishare.i_item_lend_order.class_id</code>.
     */
    public final TableField<IItemLendOrderRecord, Long> CLASS_ID = createField("class_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>ishare.i_item_lend_order.student_id</code>.
     */
    public final TableField<IItemLendOrderRecord, Long> STUDENT_ID = createField("student_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>ishare.i_item_lend_order.status</code>.
     */
    public final TableField<IItemLendOrderRecord, Integer> STATUS = createField("status", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("1", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>ishare.i_item_lend_order.created_at</code>.
     */
    public final TableField<IItemLendOrderRecord, Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>ishare.i_item_lend_order.updated_at</code>.
     */
    public final TableField<IItemLendOrderRecord, Timestamp> UPDATED_AT = createField("updated_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>ishare.i_item_lend_order</code> table reference
     */
    public IItemLendOrder() {
        this(DSL.name("i_item_lend_order"), null);
    }

    /**
     * Create an aliased <code>ishare.i_item_lend_order</code> table reference
     */
    public IItemLendOrder(String alias) {
        this(DSL.name(alias), I_ITEM_LEND_ORDER);
    }

    /**
     * Create an aliased <code>ishare.i_item_lend_order</code> table reference
     */
    public IItemLendOrder(Name alias) {
        this(alias, I_ITEM_LEND_ORDER);
    }

    private IItemLendOrder(Name alias, Table<IItemLendOrderRecord> aliased) {
        this(alias, aliased, null);
    }

    private IItemLendOrder(Name alias, Table<IItemLendOrderRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Ishare.ISHARE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.I_ITEM_LEND_ORDER_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<IItemLendOrderRecord, Long> getIdentity() {
        return Keys.IDENTITY_I_ITEM_LEND_ORDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<IItemLendOrderRecord> getPrimaryKey() {
        return Keys.KEY_I_ITEM_LEND_ORDER_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<IItemLendOrderRecord>> getKeys() {
        return Arrays.<UniqueKey<IItemLendOrderRecord>>asList(Keys.KEY_I_ITEM_LEND_ORDER_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IItemLendOrder as(String alias) {
        return new IItemLendOrder(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IItemLendOrder as(Name alias) {
        return new IItemLendOrder(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public IItemLendOrder rename(String name) {
        return new IItemLendOrder(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public IItemLendOrder rename(Name name) {
        return new IItemLendOrder(name, null);
    }
}
