/*
 * This file is generated by jOOQ.
*/
package com.pingyueryou.ishare.jooq.tables;


import com.pingyueryou.ishare.jooq.Indexes;
import com.pingyueryou.ishare.jooq.Ishare;
import com.pingyueryou.ishare.jooq.Keys;
import com.pingyueryou.ishare.jooq.tables.records.IItemTagItemRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IItemTagItem extends TableImpl<IItemTagItemRecord> {

    private static final long serialVersionUID = -7017383;

    /**
     * The reference instance of <code>ishare.i_item_tag_item</code>
     */
    public static final IItemTagItem I_ITEM_TAG_ITEM = new IItemTagItem();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<IItemTagItemRecord> getRecordType() {
        return IItemTagItemRecord.class;
    }

    /**
     * The column <code>ishare.i_item_tag_item.id</code>.
     */
    public final TableField<IItemTagItemRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>ishare.i_item_tag_item.item_id</code>.
     */
    public final TableField<IItemTagItemRecord, Long> ITEM_ID = createField("item_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>ishare.i_item_tag_item.tag_id</code>.
     */
    public final TableField<IItemTagItemRecord, Long> TAG_ID = createField("tag_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>ishare.i_item_tag_item.created_at</code>.
     */
    public final TableField<IItemTagItemRecord, Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>ishare.i_item_tag_item.updated_at</code>.
     */
    public final TableField<IItemTagItemRecord, Timestamp> UPDATED_AT = createField("updated_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>ishare.i_item_tag_item</code> table reference
     */
    public IItemTagItem() {
        this(DSL.name("i_item_tag_item"), null);
    }

    /**
     * Create an aliased <code>ishare.i_item_tag_item</code> table reference
     */
    public IItemTagItem(String alias) {
        this(DSL.name(alias), I_ITEM_TAG_ITEM);
    }

    /**
     * Create an aliased <code>ishare.i_item_tag_item</code> table reference
     */
    public IItemTagItem(Name alias) {
        this(alias, I_ITEM_TAG_ITEM);
    }

    private IItemTagItem(Name alias, Table<IItemTagItemRecord> aliased) {
        this(alias, aliased, null);
    }

    private IItemTagItem(Name alias, Table<IItemTagItemRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Ishare.ISHARE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.I_ITEM_TAG_ITEM_PRIMARY, Indexes.I_ITEM_TAG_ITEM_UK_ITEM_TAG_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<IItemTagItemRecord, Long> getIdentity() {
        return Keys.IDENTITY_I_ITEM_TAG_ITEM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<IItemTagItemRecord> getPrimaryKey() {
        return Keys.KEY_I_ITEM_TAG_ITEM_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<IItemTagItemRecord>> getKeys() {
        return Arrays.<UniqueKey<IItemTagItemRecord>>asList(Keys.KEY_I_ITEM_TAG_ITEM_PRIMARY, Keys.KEY_I_ITEM_TAG_ITEM_UK_ITEM_TAG_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IItemTagItem as(String alias) {
        return new IItemTagItem(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IItemTagItem as(Name alias) {
        return new IItemTagItem(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public IItemTagItem rename(String name) {
        return new IItemTagItem(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public IItemTagItem rename(Name name) {
        return new IItemTagItem(name, null);
    }
}
