/*
 * This file is generated by jOOQ.
*/
package com.pingyueryou.ishare.jooq.tables;


import com.pingyueryou.ishare.jooq.Indexes;
import com.pingyueryou.ishare.jooq.Ishare;
import com.pingyueryou.ishare.jooq.Keys;
import com.pingyueryou.ishare.jooq.tables.records.IItemRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IItem extends TableImpl<IItemRecord> {

    private static final long serialVersionUID = -359979205;

    /**
     * The reference instance of <code>ishare.i_item</code>
     */
    public static final IItem I_ITEM = new IItem();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<IItemRecord> getRecordType() {
        return IItemRecord.class;
    }

    /**
     * The column <code>ishare.i_item.id</code>.
     */
    public final TableField<IItemRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>ishare.i_item.type</code>.
     */
    public final TableField<IItemRecord, Integer> TYPE = createField("type", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>ishare.i_item.title</code>.
     */
    public final TableField<IItemRecord, String> TITLE = createField("title", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>ishare.i_item.cover_url</code>.
     */
    public final TableField<IItemRecord, String> COVER_URL = createField("cover_url", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>ishare.i_item.desc</code>.
     */
    public final TableField<IItemRecord, String> DESC = createField("desc", org.jooq.impl.SQLDataType.VARCHAR(500).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>ishare.i_item.status</code>.
     */
    public final TableField<IItemRecord, Integer> STATUS = createField("status", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("1", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>ishare.i_item.upload_user_id</code>.
     */
    public final TableField<IItemRecord, Long> UPLOAD_USER_ID = createField("upload_user_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>ishare.i_item.class_id</code>.
     */
    public final TableField<IItemRecord, Long> CLASS_ID = createField("class_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>ishare.i_item.created_at</code>.
     */
    public final TableField<IItemRecord, Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>ishare.i_item.updated_at</code>.
     */
    public final TableField<IItemRecord, Timestamp> UPDATED_AT = createField("updated_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>ishare.i_item</code> table reference
     */
    public IItem() {
        this(DSL.name("i_item"), null);
    }

    /**
     * Create an aliased <code>ishare.i_item</code> table reference
     */
    public IItem(String alias) {
        this(DSL.name(alias), I_ITEM);
    }

    /**
     * Create an aliased <code>ishare.i_item</code> table reference
     */
    public IItem(Name alias) {
        this(alias, I_ITEM);
    }

    private IItem(Name alias, Table<IItemRecord> aliased) {
        this(alias, aliased, null);
    }

    private IItem(Name alias, Table<IItemRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Ishare.ISHARE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.I_ITEM_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<IItemRecord, Long> getIdentity() {
        return Keys.IDENTITY_I_ITEM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<IItemRecord> getPrimaryKey() {
        return Keys.KEY_I_ITEM_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<IItemRecord>> getKeys() {
        return Arrays.<UniqueKey<IItemRecord>>asList(Keys.KEY_I_ITEM_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IItem as(String alias) {
        return new IItem(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IItem as(Name alias) {
        return new IItem(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public IItem rename(String name) {
        return new IItem(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public IItem rename(Name name) {
        return new IItem(name, null);
    }
}
