/*
 * This file is generated by jOOQ.
*/
package com.pingyueryou.ishare.jooq.tables;


import com.pingyueryou.ishare.jooq.Indexes;
import com.pingyueryou.ishare.jooq.Ishare;
import com.pingyueryou.ishare.jooq.Keys;
import com.pingyueryou.ishare.jooq.tables.records.IItemTagRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IItemTag extends TableImpl<IItemTagRecord> {

    private static final long serialVersionUID = 1709355561;

    /**
     * The reference instance of <code>ishare.i_item_tag</code>
     */
    public static final IItemTag I_ITEM_TAG = new IItemTag();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<IItemTagRecord> getRecordType() {
        return IItemTagRecord.class;
    }

    /**
     * The column <code>ishare.i_item_tag.id</code>.
     */
    public final TableField<IItemTagRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>ishare.i_item_tag.name</code>.
     */
    public final TableField<IItemTagRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(200).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>ishare.i_item_tag.created_at</code>.
     */
    public final TableField<IItemTagRecord, Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>ishare.i_item_tag.updated_at</code>.
     */
    public final TableField<IItemTagRecord, Timestamp> UPDATED_AT = createField("updated_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>ishare.i_item_tag</code> table reference
     */
    public IItemTag() {
        this(DSL.name("i_item_tag"), null);
    }

    /**
     * Create an aliased <code>ishare.i_item_tag</code> table reference
     */
    public IItemTag(String alias) {
        this(DSL.name(alias), I_ITEM_TAG);
    }

    /**
     * Create an aliased <code>ishare.i_item_tag</code> table reference
     */
    public IItemTag(Name alias) {
        this(alias, I_ITEM_TAG);
    }

    private IItemTag(Name alias, Table<IItemTagRecord> aliased) {
        this(alias, aliased, null);
    }

    private IItemTag(Name alias, Table<IItemTagRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Ishare.ISHARE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.I_ITEM_TAG_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<IItemTagRecord, Long> getIdentity() {
        return Keys.IDENTITY_I_ITEM_TAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<IItemTagRecord> getPrimaryKey() {
        return Keys.KEY_I_ITEM_TAG_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<IItemTagRecord>> getKeys() {
        return Arrays.<UniqueKey<IItemTagRecord>>asList(Keys.KEY_I_ITEM_TAG_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IItemTag as(String alias) {
        return new IItemTag(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IItemTag as(Name alias) {
        return new IItemTag(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public IItemTag rename(String name) {
        return new IItemTag(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public IItemTag rename(Name name) {
        return new IItemTag(name, null);
    }
}
