/*
 * This file is generated by jOOQ.
*/
package com.pingyueryou.ishare.jooq.tables;


import com.pingyueryou.ishare.jooq.Indexes;
import com.pingyueryou.ishare.jooq.Ishare;
import com.pingyueryou.ishare.jooq.Keys;
import com.pingyueryou.ishare.jooq.tables.records.IRoleRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IRole extends TableImpl<IRoleRecord> {

    private static final long serialVersionUID = 1057730493;

    /**
     * The reference instance of <code>ishare.i_role</code>
     */
    public static final IRole I_ROLE = new IRole();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<IRoleRecord> getRecordType() {
        return IRoleRecord.class;
    }

    /**
     * The column <code>ishare.i_role.id</code>.
     */
    public final TableField<IRoleRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>ishare.i_role.name</code>.
     */
    public final TableField<IRoleRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(200).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>ishare.i_role.created_at</code>.
     */
    public final TableField<IRoleRecord, Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>ishare.i_role.updated_at</code>.
     */
    public final TableField<IRoleRecord, Timestamp> UPDATED_AT = createField("updated_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>ishare.i_role</code> table reference
     */
    public IRole() {
        this(DSL.name("i_role"), null);
    }

    /**
     * Create an aliased <code>ishare.i_role</code> table reference
     */
    public IRole(String alias) {
        this(DSL.name(alias), I_ROLE);
    }

    /**
     * Create an aliased <code>ishare.i_role</code> table reference
     */
    public IRole(Name alias) {
        this(alias, I_ROLE);
    }

    private IRole(Name alias, Table<IRoleRecord> aliased) {
        this(alias, aliased, null);
    }

    private IRole(Name alias, Table<IRoleRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Ishare.ISHARE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.I_ROLE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<IRoleRecord, Long> getIdentity() {
        return Keys.IDENTITY_I_ROLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<IRoleRecord> getPrimaryKey() {
        return Keys.KEY_I_ROLE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<IRoleRecord>> getKeys() {
        return Arrays.<UniqueKey<IRoleRecord>>asList(Keys.KEY_I_ROLE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IRole as(String alias) {
        return new IRole(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IRole as(Name alias) {
        return new IRole(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public IRole rename(String name) {
        return new IRole(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public IRole rename(Name name) {
        return new IRole(name, null);
    }
}
