/*
 * This file is generated by jOOQ.
*/
package com.pingyueryou.ishare.jooq.tables;


import com.pingyueryou.ishare.jooq.Indexes;
import com.pingyueryou.ishare.jooq.Ishare;
import com.pingyueryou.ishare.jooq.Keys;
import com.pingyueryou.ishare.jooq.tables.records.IShareCommentRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IShareComment extends TableImpl<IShareCommentRecord> {

    private static final long serialVersionUID = 2077567503;

    /**
     * The reference instance of <code>ishare.i_share_comment</code>
     */
    public static final IShareComment I_SHARE_COMMENT = new IShareComment();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<IShareCommentRecord> getRecordType() {
        return IShareCommentRecord.class;
    }

    /**
     * The column <code>ishare.i_share_comment.id</code>.
     */
    public final TableField<IShareCommentRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>ishare.i_share_comment.share_id</code>.
     */
    public final TableField<IShareCommentRecord, Long> SHARE_ID = createField("share_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>ishare.i_share_comment.user_id</code>.
     */
    public final TableField<IShareCommentRecord, Long> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>ishare.i_share_comment.comment</code>.
     */
    public final TableField<IShareCommentRecord, String> COMMENT = createField("comment", org.jooq.impl.SQLDataType.VARCHAR(1000).nullable(false), this, "");

    /**
     * The column <code>ishare.i_share_comment.created_at</code>.
     */
    public final TableField<IShareCommentRecord, Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>ishare.i_share_comment.updated_at</code>.
     */
    public final TableField<IShareCommentRecord, Timestamp> UPDATED_AT = createField("updated_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>ishare.i_share_comment</code> table reference
     */
    public IShareComment() {
        this(DSL.name("i_share_comment"), null);
    }

    /**
     * Create an aliased <code>ishare.i_share_comment</code> table reference
     */
    public IShareComment(String alias) {
        this(DSL.name(alias), I_SHARE_COMMENT);
    }

    /**
     * Create an aliased <code>ishare.i_share_comment</code> table reference
     */
    public IShareComment(Name alias) {
        this(alias, I_SHARE_COMMENT);
    }

    private IShareComment(Name alias, Table<IShareCommentRecord> aliased) {
        this(alias, aliased, null);
    }

    private IShareComment(Name alias, Table<IShareCommentRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Ishare.ISHARE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.I_SHARE_COMMENT_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<IShareCommentRecord, Long> getIdentity() {
        return Keys.IDENTITY_I_SHARE_COMMENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<IShareCommentRecord> getPrimaryKey() {
        return Keys.KEY_I_SHARE_COMMENT_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<IShareCommentRecord>> getKeys() {
        return Arrays.<UniqueKey<IShareCommentRecord>>asList(Keys.KEY_I_SHARE_COMMENT_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IShareComment as(String alias) {
        return new IShareComment(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IShareComment as(Name alias) {
        return new IShareComment(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public IShareComment rename(String name) {
        return new IShareComment(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public IShareComment rename(Name name) {
        return new IShareComment(name, null);
    }
}
