/*
 * This file is generated by jOOQ.
*/
package com.pingyueryou.ishare.jooq.tables;


import com.pingyueryou.ishare.jooq.Indexes;
import com.pingyueryou.ishare.jooq.Ishare;
import com.pingyueryou.ishare.jooq.Keys;
import com.pingyueryou.ishare.jooq.tables.records.IShareMediaRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IShareMedia extends TableImpl<IShareMediaRecord> {

    private static final long serialVersionUID = -525626883;

    /**
     * The reference instance of <code>ishare.i_share_media</code>
     */
    public static final IShareMedia I_SHARE_MEDIA = new IShareMedia();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<IShareMediaRecord> getRecordType() {
        return IShareMediaRecord.class;
    }

    /**
     * The column <code>ishare.i_share_media.id</code>.
     */
    public final TableField<IShareMediaRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>ishare.i_share_media.path</code>.
     */
    public final TableField<IShareMediaRecord, String> PATH = createField("path", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>ishare.i_share_media.duration</code>.
     */
    public final TableField<IShareMediaRecord, Integer> DURATION = createField("duration", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>ishare.i_share_media.size</code>.
     */
    public final TableField<IShareMediaRecord, Integer> SIZE = createField("size", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>ishare.i_share_media.width</code>.
     */
    public final TableField<IShareMediaRecord, Integer> WIDTH = createField("width", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>ishare.i_share_media.height</code>.
     */
    public final TableField<IShareMediaRecord, Integer> HEIGHT = createField("height", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>ishare.i_share_media.created_at</code>.
     */
    public final TableField<IShareMediaRecord, Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>ishare.i_share_media.updated_at</code>.
     */
    public final TableField<IShareMediaRecord, Timestamp> UPDATED_AT = createField("updated_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>ishare.i_share_media</code> table reference
     */
    public IShareMedia() {
        this(DSL.name("i_share_media"), null);
    }

    /**
     * Create an aliased <code>ishare.i_share_media</code> table reference
     */
    public IShareMedia(String alias) {
        this(DSL.name(alias), I_SHARE_MEDIA);
    }

    /**
     * Create an aliased <code>ishare.i_share_media</code> table reference
     */
    public IShareMedia(Name alias) {
        this(alias, I_SHARE_MEDIA);
    }

    private IShareMedia(Name alias, Table<IShareMediaRecord> aliased) {
        this(alias, aliased, null);
    }

    private IShareMedia(Name alias, Table<IShareMediaRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Ishare.ISHARE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.I_SHARE_MEDIA_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<IShareMediaRecord, Long> getIdentity() {
        return Keys.IDENTITY_I_SHARE_MEDIA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<IShareMediaRecord> getPrimaryKey() {
        return Keys.KEY_I_SHARE_MEDIA_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<IShareMediaRecord>> getKeys() {
        return Arrays.<UniqueKey<IShareMediaRecord>>asList(Keys.KEY_I_SHARE_MEDIA_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IShareMedia as(String alias) {
        return new IShareMedia(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IShareMedia as(Name alias) {
        return new IShareMedia(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public IShareMedia rename(String name) {
        return new IShareMedia(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public IShareMedia rename(Name name) {
        return new IShareMedia(name, null);
    }
}
