/*
 * This file is generated by jOOQ.
*/
package com.pingyueryou.ishare.jooq.tables;


import com.pingyueryou.ishare.jooq.Indexes;
import com.pingyueryou.ishare.jooq.Ishare;
import com.pingyueryou.ishare.jooq.Keys;
import com.pingyueryou.ishare.jooq.tables.records.IShareLikeRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IShareLike extends TableImpl<IShareLikeRecord> {

    private static final long serialVersionUID = -1300833035;

    /**
     * The reference instance of <code>ishare.i_share_like</code>
     */
    public static final IShareLike I_SHARE_LIKE = new IShareLike();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<IShareLikeRecord> getRecordType() {
        return IShareLikeRecord.class;
    }

    /**
     * The column <code>ishare.i_share_like.id</code>.
     */
    public final TableField<IShareLikeRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>ishare.i_share_like.share_id</code>.
     */
    public final TableField<IShareLikeRecord, Long> SHARE_ID = createField("share_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>ishare.i_share_like.user_id</code>.
     */
    public final TableField<IShareLikeRecord, Long> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>ishare.i_share_like.created_at</code>.
     */
    public final TableField<IShareLikeRecord, Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>ishare.i_share_like.updated_at</code>.
     */
    public final TableField<IShareLikeRecord, Timestamp> UPDATED_AT = createField("updated_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>ishare.i_share_like</code> table reference
     */
    public IShareLike() {
        this(DSL.name("i_share_like"), null);
    }

    /**
     * Create an aliased <code>ishare.i_share_like</code> table reference
     */
    public IShareLike(String alias) {
        this(DSL.name(alias), I_SHARE_LIKE);
    }

    /**
     * Create an aliased <code>ishare.i_share_like</code> table reference
     */
    public IShareLike(Name alias) {
        this(alias, I_SHARE_LIKE);
    }

    private IShareLike(Name alias, Table<IShareLikeRecord> aliased) {
        this(alias, aliased, null);
    }

    private IShareLike(Name alias, Table<IShareLikeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Ishare.ISHARE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.I_SHARE_LIKE_PRIMARY, Indexes.I_SHARE_LIKE_UK_SHARE_USER_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<IShareLikeRecord, Long> getIdentity() {
        return Keys.IDENTITY_I_SHARE_LIKE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<IShareLikeRecord> getPrimaryKey() {
        return Keys.KEY_I_SHARE_LIKE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<IShareLikeRecord>> getKeys() {
        return Arrays.<UniqueKey<IShareLikeRecord>>asList(Keys.KEY_I_SHARE_LIKE_PRIMARY, Keys.KEY_I_SHARE_LIKE_UK_SHARE_USER_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IShareLike as(String alias) {
        return new IShareLike(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IShareLike as(Name alias) {
        return new IShareLike(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public IShareLike rename(String name) {
        return new IShareLike(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public IShareLike rename(Name name) {
        return new IShareLike(name, null);
    }
}
