/*
 * This file is generated by jOOQ.
*/
package com.pingyueryou.ishare.jooq.tables;


import com.pingyueryou.ishare.jooq.Indexes;
import com.pingyueryou.ishare.jooq.Ishare;
import com.pingyueryou.ishare.jooq.Keys;
import com.pingyueryou.ishare.jooq.tables.records.IUserStudentRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IUserStudent extends TableImpl<IUserStudentRecord> {

    private static final long serialVersionUID = 1945640602;

    /**
     * The reference instance of <code>ishare.i_user_student</code>
     */
    public static final IUserStudent I_USER_STUDENT = new IUserStudent();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<IUserStudentRecord> getRecordType() {
        return IUserStudentRecord.class;
    }

    /**
     * The column <code>ishare.i_user_student.id</code>.
     */
    public final TableField<IUserStudentRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>ishare.i_user_student.user_id</code>.
     */
    public final TableField<IUserStudentRecord, Long> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>ishare.i_user_student.student_id</code>.
     */
    public final TableField<IUserStudentRecord, Long> STUDENT_ID = createField("student_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>ishare.i_user_student.relation</code>.
     */
    public final TableField<IUserStudentRecord, String> RELATION = createField("relation", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>ishare.i_user_student.created_at</code>.
     */
    public final TableField<IUserStudentRecord, Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>ishare.i_user_student.updated_at</code>.
     */
    public final TableField<IUserStudentRecord, Timestamp> UPDATED_AT = createField("updated_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>ishare.i_user_student</code> table reference
     */
    public IUserStudent() {
        this(DSL.name("i_user_student"), null);
    }

    /**
     * Create an aliased <code>ishare.i_user_student</code> table reference
     */
    public IUserStudent(String alias) {
        this(DSL.name(alias), I_USER_STUDENT);
    }

    /**
     * Create an aliased <code>ishare.i_user_student</code> table reference
     */
    public IUserStudent(Name alias) {
        this(alias, I_USER_STUDENT);
    }

    private IUserStudent(Name alias, Table<IUserStudentRecord> aliased) {
        this(alias, aliased, null);
    }

    private IUserStudent(Name alias, Table<IUserStudentRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Ishare.ISHARE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.I_USER_STUDENT_PRIMARY, Indexes.I_USER_STUDENT_UK_USER_STUDENT_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<IUserStudentRecord, Long> getIdentity() {
        return Keys.IDENTITY_I_USER_STUDENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<IUserStudentRecord> getPrimaryKey() {
        return Keys.KEY_I_USER_STUDENT_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<IUserStudentRecord>> getKeys() {
        return Arrays.<UniqueKey<IUserStudentRecord>>asList(Keys.KEY_I_USER_STUDENT_PRIMARY, Keys.KEY_I_USER_STUDENT_UK_USER_STUDENT_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IUserStudent as(String alias) {
        return new IUserStudent(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IUserStudent as(Name alias) {
        return new IUserStudent(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public IUserStudent rename(String name) {
        return new IUserStudent(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public IUserStudent rename(Name name) {
        return new IUserStudent(name, null);
    }
}
