/*
 * This file is generated by jOOQ.
*/
package com.pingyueryou.ishare.jooq.tables;


import com.pingyueryou.ishare.jooq.Indexes;
import com.pingyueryou.ishare.jooq.Ishare;
import com.pingyueryou.ishare.jooq.Keys;
import com.pingyueryou.ishare.jooq.tables.records.IUserRoleRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IUserRole extends TableImpl<IUserRoleRecord> {

    private static final long serialVersionUID = -1057226188;

    /**
     * The reference instance of <code>ishare.i_user_role</code>
     */
    public static final IUserRole I_USER_ROLE = new IUserRole();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<IUserRoleRecord> getRecordType() {
        return IUserRoleRecord.class;
    }

    /**
     * The column <code>ishare.i_user_role.id</code>.
     */
    public final TableField<IUserRoleRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>ishare.i_user_role.user_id</code>.
     */
    public final TableField<IUserRoleRecord, Long> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>ishare.i_user_role.role</code>.
     */
    public final TableField<IUserRoleRecord, Integer> ROLE = createField("role", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("1", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>ishare.i_user_role.created_at</code>.
     */
    public final TableField<IUserRoleRecord, Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>ishare.i_user_role.updated_at</code>.
     */
    public final TableField<IUserRoleRecord, Timestamp> UPDATED_AT = createField("updated_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>ishare.i_user_role</code> table reference
     */
    public IUserRole() {
        this(DSL.name("i_user_role"), null);
    }

    /**
     * Create an aliased <code>ishare.i_user_role</code> table reference
     */
    public IUserRole(String alias) {
        this(DSL.name(alias), I_USER_ROLE);
    }

    /**
     * Create an aliased <code>ishare.i_user_role</code> table reference
     */
    public IUserRole(Name alias) {
        this(alias, I_USER_ROLE);
    }

    private IUserRole(Name alias, Table<IUserRoleRecord> aliased) {
        this(alias, aliased, null);
    }

    private IUserRole(Name alias, Table<IUserRoleRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Ishare.ISHARE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.I_USER_ROLE_PRIMARY, Indexes.I_USER_ROLE_UK_USER_ID_ROLE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<IUserRoleRecord, Long> getIdentity() {
        return Keys.IDENTITY_I_USER_ROLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<IUserRoleRecord> getPrimaryKey() {
        return Keys.KEY_I_USER_ROLE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<IUserRoleRecord>> getKeys() {
        return Arrays.<UniqueKey<IUserRoleRecord>>asList(Keys.KEY_I_USER_ROLE_PRIMARY, Keys.KEY_I_USER_ROLE_UK_USER_ID_ROLE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IUserRole as(String alias) {
        return new IUserRole(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IUserRole as(Name alias) {
        return new IUserRole(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public IUserRole rename(String name) {
        return new IUserRole(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public IUserRole rename(Name name) {
        return new IUserRole(name, null);
    }
}
