/*
 * This file is generated by jOOQ.
*/
package com.pingyueryou.ishare.jooq.tables.daos;


import com.pingyueryou.ishare.jooq.tables.IGrade;
import com.pingyueryou.ishare.jooq.tables.records.IGradeRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IGradeDao extends DAOImpl<IGradeRecord, com.pingyueryou.ishare.jooq.tables.pojos.IGrade, Long> {

    /**
     * Create a new IGradeDao without any configuration
     */
    public IGradeDao() {
        super(IGrade.I_GRADE, com.pingyueryou.ishare.jooq.tables.pojos.IGrade.class);
    }

    /**
     * Create a new IGradeDao with an attached configuration
     */
    public IGradeDao(Configuration configuration) {
        super(IGrade.I_GRADE, com.pingyueryou.ishare.jooq.tables.pojos.IGrade.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(com.pingyueryou.ishare.jooq.tables.pojos.IGrade object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.pingyueryou.ishare.jooq.tables.pojos.IGrade> fetchById(Long... values) {
        return fetch(IGrade.I_GRADE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.pingyueryou.ishare.jooq.tables.pojos.IGrade fetchOneById(Long value) {
        return fetchOne(IGrade.I_GRADE.ID, value);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.pingyueryou.ishare.jooq.tables.pojos.IGrade> fetchByName(String... values) {
        return fetch(IGrade.I_GRADE.NAME, values);
    }

    /**
     * Fetch records that have <code>order IN (values)</code>
     */
    public List<com.pingyueryou.ishare.jooq.tables.pojos.IGrade> fetchByOrder(Integer... values) {
        return fetch(IGrade.I_GRADE.ORDER, values);
    }

    /**
     * Fetch records that have <code>created_at IN (values)</code>
     */
    public List<com.pingyueryou.ishare.jooq.tables.pojos.IGrade> fetchByCreatedAt(Timestamp... values) {
        return fetch(IGrade.I_GRADE.CREATED_AT, values);
    }

    /**
     * Fetch records that have <code>updated_at IN (values)</code>
     */
    public List<com.pingyueryou.ishare.jooq.tables.pojos.IGrade> fetchByUpdatedAt(Timestamp... values) {
        return fetch(IGrade.I_GRADE.UPDATED_AT, values);
    }
}
