/*
 * This file is generated by jOOQ.
*/
package com.pingyueryou.ishare.jooq.tables.daos;


import com.pingyueryou.ishare.jooq.tables.IItemLendOrder;
import com.pingyueryou.ishare.jooq.tables.records.IItemLendOrderRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IItemLendOrderDao extends DAOImpl<IItemLendOrderRecord, com.pingyueryou.ishare.jooq.tables.pojos.IItemLendOrder, Long> {

    /**
     * Create a new IItemLendOrderDao without any configuration
     */
    public IItemLendOrderDao() {
        super(IItemLendOrder.I_ITEM_LEND_ORDER, com.pingyueryou.ishare.jooq.tables.pojos.IItemLendOrder.class);
    }

    /**
     * Create a new IItemLendOrderDao with an attached configuration
     */
    public IItemLendOrderDao(Configuration configuration) {
        super(IItemLendOrder.I_ITEM_LEND_ORDER, com.pingyueryou.ishare.jooq.tables.pojos.IItemLendOrder.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(com.pingyueryou.ishare.jooq.tables.pojos.IItemLendOrder object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.pingyueryou.ishare.jooq.tables.pojos.IItemLendOrder> fetchById(Long... values) {
        return fetch(IItemLendOrder.I_ITEM_LEND_ORDER.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.pingyueryou.ishare.jooq.tables.pojos.IItemLendOrder fetchOneById(Long value) {
        return fetchOne(IItemLendOrder.I_ITEM_LEND_ORDER.ID, value);
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<com.pingyueryou.ishare.jooq.tables.pojos.IItemLendOrder> fetchByUserId(Long... values) {
        return fetch(IItemLendOrder.I_ITEM_LEND_ORDER.USER_ID, values);
    }

    /**
     * Fetch records that have <code>item_id IN (values)</code>
     */
    public List<com.pingyueryou.ishare.jooq.tables.pojos.IItemLendOrder> fetchByItemId(Long... values) {
        return fetch(IItemLendOrder.I_ITEM_LEND_ORDER.ITEM_ID, values);
    }

    /**
     * Fetch records that have <code>class_id IN (values)</code>
     */
    public List<com.pingyueryou.ishare.jooq.tables.pojos.IItemLendOrder> fetchByClassId(Long... values) {
        return fetch(IItemLendOrder.I_ITEM_LEND_ORDER.CLASS_ID, values);
    }

    /**
     * Fetch records that have <code>student_id IN (values)</code>
     */
    public List<com.pingyueryou.ishare.jooq.tables.pojos.IItemLendOrder> fetchByStudentId(Long... values) {
        return fetch(IItemLendOrder.I_ITEM_LEND_ORDER.STUDENT_ID, values);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<com.pingyueryou.ishare.jooq.tables.pojos.IItemLendOrder> fetchByStatus(Integer... values) {
        return fetch(IItemLendOrder.I_ITEM_LEND_ORDER.STATUS, values);
    }

    /**
     * Fetch records that have <code>created_at IN (values)</code>
     */
    public List<com.pingyueryou.ishare.jooq.tables.pojos.IItemLendOrder> fetchByCreatedAt(Timestamp... values) {
        return fetch(IItemLendOrder.I_ITEM_LEND_ORDER.CREATED_AT, values);
    }

    /**
     * Fetch records that have <code>updated_at IN (values)</code>
     */
    public List<com.pingyueryou.ishare.jooq.tables.pojos.IItemLendOrder> fetchByUpdatedAt(Timestamp... values) {
        return fetch(IItemLendOrder.I_ITEM_LEND_ORDER.UPDATED_AT, values);
    }
}
