/*
 * This file is generated by jOOQ.
*/
package com.pingyueryou.ishare.jooq.tables.daos;


import com.pingyueryou.ishare.jooq.tables.IItemTagItem;
import com.pingyueryou.ishare.jooq.tables.records.IItemTagItemRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IItemTagItemDao extends DAOImpl<IItemTagItemRecord, com.pingyueryou.ishare.jooq.tables.pojos.IItemTagItem, Long> {

    /**
     * Create a new IItemTagItemDao without any configuration
     */
    public IItemTagItemDao() {
        super(IItemTagItem.I_ITEM_TAG_ITEM, com.pingyueryou.ishare.jooq.tables.pojos.IItemTagItem.class);
    }

    /**
     * Create a new IItemTagItemDao with an attached configuration
     */
    public IItemTagItemDao(Configuration configuration) {
        super(IItemTagItem.I_ITEM_TAG_ITEM, com.pingyueryou.ishare.jooq.tables.pojos.IItemTagItem.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(com.pingyueryou.ishare.jooq.tables.pojos.IItemTagItem object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.pingyueryou.ishare.jooq.tables.pojos.IItemTagItem> fetchById(Long... values) {
        return fetch(IItemTagItem.I_ITEM_TAG_ITEM.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.pingyueryou.ishare.jooq.tables.pojos.IItemTagItem fetchOneById(Long value) {
        return fetchOne(IItemTagItem.I_ITEM_TAG_ITEM.ID, value);
    }

    /**
     * Fetch records that have <code>item_id IN (values)</code>
     */
    public List<com.pingyueryou.ishare.jooq.tables.pojos.IItemTagItem> fetchByItemId(Long... values) {
        return fetch(IItemTagItem.I_ITEM_TAG_ITEM.ITEM_ID, values);
    }

    /**
     * Fetch records that have <code>tag_id IN (values)</code>
     */
    public List<com.pingyueryou.ishare.jooq.tables.pojos.IItemTagItem> fetchByTagId(Long... values) {
        return fetch(IItemTagItem.I_ITEM_TAG_ITEM.TAG_ID, values);
    }

    /**
     * Fetch records that have <code>created_at IN (values)</code>
     */
    public List<com.pingyueryou.ishare.jooq.tables.pojos.IItemTagItem> fetchByCreatedAt(Timestamp... values) {
        return fetch(IItemTagItem.I_ITEM_TAG_ITEM.CREATED_AT, values);
    }

    /**
     * Fetch records that have <code>updated_at IN (values)</code>
     */
    public List<com.pingyueryou.ishare.jooq.tables.pojos.IItemTagItem> fetchByUpdatedAt(Timestamp... values) {
        return fetch(IItemTagItem.I_ITEM_TAG_ITEM.UPDATED_AT, values);
    }
}
