/*
 * This file is generated by jOOQ.
*/
package com.pingyueryou.ishare.jooq.tables.daos;


import com.pingyueryou.ishare.jooq.tables.IItemTag;
import com.pingyueryou.ishare.jooq.tables.records.IItemTagRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IItemTagDao extends DAOImpl<IItemTagRecord, com.pingyueryou.ishare.jooq.tables.pojos.IItemTag, Long> {

    /**
     * Create a new IItemTagDao without any configuration
     */
    public IItemTagDao() {
        super(IItemTag.I_ITEM_TAG, com.pingyueryou.ishare.jooq.tables.pojos.IItemTag.class);
    }

    /**
     * Create a new IItemTagDao with an attached configuration
     */
    public IItemTagDao(Configuration configuration) {
        super(IItemTag.I_ITEM_TAG, com.pingyueryou.ishare.jooq.tables.pojos.IItemTag.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(com.pingyueryou.ishare.jooq.tables.pojos.IItemTag object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.pingyueryou.ishare.jooq.tables.pojos.IItemTag> fetchById(Long... values) {
        return fetch(IItemTag.I_ITEM_TAG.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.pingyueryou.ishare.jooq.tables.pojos.IItemTag fetchOneById(Long value) {
        return fetchOne(IItemTag.I_ITEM_TAG.ID, value);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.pingyueryou.ishare.jooq.tables.pojos.IItemTag> fetchByName(String... values) {
        return fetch(IItemTag.I_ITEM_TAG.NAME, values);
    }

    /**
     * Fetch records that have <code>created_at IN (values)</code>
     */
    public List<com.pingyueryou.ishare.jooq.tables.pojos.IItemTag> fetchByCreatedAt(Timestamp... values) {
        return fetch(IItemTag.I_ITEM_TAG.CREATED_AT, values);
    }

    /**
     * Fetch records that have <code>updated_at IN (values)</code>
     */
    public List<com.pingyueryou.ishare.jooq.tables.pojos.IItemTag> fetchByUpdatedAt(Timestamp... values) {
        return fetch(IItemTag.I_ITEM_TAG.UPDATED_AT, values);
    }
}
