/*
 * This file is generated by jOOQ.
*/
package com.pingyueryou.ishare.jooq.tables.daos;


import com.pingyueryou.ishare.jooq.tables.IRole;
import com.pingyueryou.ishare.jooq.tables.records.IRoleRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IRoleDao extends DAOImpl<IRoleRecord, com.pingyueryou.ishare.jooq.tables.pojos.IRole, Long> {

    /**
     * Create a new IRoleDao without any configuration
     */
    public IRoleDao() {
        super(IRole.I_ROLE, com.pingyueryou.ishare.jooq.tables.pojos.IRole.class);
    }

    /**
     * Create a new IRoleDao with an attached configuration
     */
    public IRoleDao(Configuration configuration) {
        super(IRole.I_ROLE, com.pingyueryou.ishare.jooq.tables.pojos.IRole.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(com.pingyueryou.ishare.jooq.tables.pojos.IRole object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.pingyueryou.ishare.jooq.tables.pojos.IRole> fetchById(Long... values) {
        return fetch(IRole.I_ROLE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.pingyueryou.ishare.jooq.tables.pojos.IRole fetchOneById(Long value) {
        return fetchOne(IRole.I_ROLE.ID, value);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.pingyueryou.ishare.jooq.tables.pojos.IRole> fetchByName(String... values) {
        return fetch(IRole.I_ROLE.NAME, values);
    }

    /**
     * Fetch records that have <code>created_at IN (values)</code>
     */
    public List<com.pingyueryou.ishare.jooq.tables.pojos.IRole> fetchByCreatedAt(Timestamp... values) {
        return fetch(IRole.I_ROLE.CREATED_AT, values);
    }

    /**
     * Fetch records that have <code>updated_at IN (values)</code>
     */
    public List<com.pingyueryou.ishare.jooq.tables.pojos.IRole> fetchByUpdatedAt(Timestamp... values) {
        return fetch(IRole.I_ROLE.UPDATED_AT, values);
    }
}
