/*
 * This file is generated by jOOQ.
*/
package com.pingyueryou.ishare.jooq.tables.daos;


import com.pingyueryou.ishare.jooq.tables.IShare;
import com.pingyueryou.ishare.jooq.tables.records.IShareRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IShareDao extends DAOImpl<IShareRecord, com.pingyueryou.ishare.jooq.tables.pojos.IShare, Long> {

    /**
     * Create a new IShareDao without any configuration
     */
    public IShareDao() {
        super(IShare.I_SHARE, com.pingyueryou.ishare.jooq.tables.pojos.IShare.class);
    }

    /**
     * Create a new IShareDao with an attached configuration
     */
    public IShareDao(Configuration configuration) {
        super(IShare.I_SHARE, com.pingyueryou.ishare.jooq.tables.pojos.IShare.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(com.pingyueryou.ishare.jooq.tables.pojos.IShare object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.pingyueryou.ishare.jooq.tables.pojos.IShare> fetchById(Long... values) {
        return fetch(IShare.I_SHARE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.pingyueryou.ishare.jooq.tables.pojos.IShare fetchOneById(Long value) {
        return fetchOne(IShare.I_SHARE.ID, value);
    }

    /**
     * Fetch records that have <code>title IN (values)</code>
     */
    public List<com.pingyueryou.ishare.jooq.tables.pojos.IShare> fetchByTitle(String... values) {
        return fetch(IShare.I_SHARE.TITLE, values);
    }

    /**
     * Fetch records that have <code>media_url IN (values)</code>
     */
    public List<com.pingyueryou.ishare.jooq.tables.pojos.IShare> fetchByMediaUrl(String... values) {
        return fetch(IShare.I_SHARE.MEDIA_URL, values);
    }

    /**
     * Fetch records that have <code>media_type IN (values)</code>
     */
    public List<com.pingyueryou.ishare.jooq.tables.pojos.IShare> fetchByMediaType(Integer... values) {
        return fetch(IShare.I_SHARE.MEDIA_TYPE, values);
    }

    /**
     * Fetch records that have <code>upload_user_id IN (values)</code>
     */
    public List<com.pingyueryou.ishare.jooq.tables.pojos.IShare> fetchByUploadUserId(Long... values) {
        return fetch(IShare.I_SHARE.UPLOAD_USER_ID, values);
    }

    /**
     * Fetch records that have <code>class_id IN (values)</code>
     */
    public List<com.pingyueryou.ishare.jooq.tables.pojos.IShare> fetchByClassId(Long... values) {
        return fetch(IShare.I_SHARE.CLASS_ID, values);
    }

    /**
     * Fetch records that have <code>item_id IN (values)</code>
     */
    public List<com.pingyueryou.ishare.jooq.tables.pojos.IShare> fetchByItemId(Long... values) {
        return fetch(IShare.I_SHARE.ITEM_ID, values);
    }

    /**
     * Fetch records that have <code>desc IN (values)</code>
     */
    public List<com.pingyueryou.ishare.jooq.tables.pojos.IShare> fetchByDesc(String... values) {
        return fetch(IShare.I_SHARE.DESC, values);
    }

    /**
     * Fetch records that have <code>created_at IN (values)</code>
     */
    public List<com.pingyueryou.ishare.jooq.tables.pojos.IShare> fetchByCreatedAt(Timestamp... values) {
        return fetch(IShare.I_SHARE.CREATED_AT, values);
    }

    /**
     * Fetch records that have <code>updated_at IN (values)</code>
     */
    public List<com.pingyueryou.ishare.jooq.tables.pojos.IShare> fetchByUpdatedAt(Timestamp... values) {
        return fetch(IShare.I_SHARE.UPDATED_AT, values);
    }
}
