/*
 * This file is generated by jOOQ.
*/
package com.pingyueryou.ishare.jooq.tables.daos;


import com.pingyueryou.ishare.jooq.tables.IShareComment;
import com.pingyueryou.ishare.jooq.tables.records.IShareCommentRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IShareCommentDao extends DAOImpl<IShareCommentRecord, com.pingyueryou.ishare.jooq.tables.pojos.IShareComment, Long> {

    /**
     * Create a new IShareCommentDao without any configuration
     */
    public IShareCommentDao() {
        super(IShareComment.I_SHARE_COMMENT, com.pingyueryou.ishare.jooq.tables.pojos.IShareComment.class);
    }

    /**
     * Create a new IShareCommentDao with an attached configuration
     */
    public IShareCommentDao(Configuration configuration) {
        super(IShareComment.I_SHARE_COMMENT, com.pingyueryou.ishare.jooq.tables.pojos.IShareComment.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(com.pingyueryou.ishare.jooq.tables.pojos.IShareComment object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.pingyueryou.ishare.jooq.tables.pojos.IShareComment> fetchById(Long... values) {
        return fetch(IShareComment.I_SHARE_COMMENT.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.pingyueryou.ishare.jooq.tables.pojos.IShareComment fetchOneById(Long value) {
        return fetchOne(IShareComment.I_SHARE_COMMENT.ID, value);
    }

    /**
     * Fetch records that have <code>share_id IN (values)</code>
     */
    public List<com.pingyueryou.ishare.jooq.tables.pojos.IShareComment> fetchByShareId(Long... values) {
        return fetch(IShareComment.I_SHARE_COMMENT.SHARE_ID, values);
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<com.pingyueryou.ishare.jooq.tables.pojos.IShareComment> fetchByUserId(Long... values) {
        return fetch(IShareComment.I_SHARE_COMMENT.USER_ID, values);
    }

    /**
     * Fetch records that have <code>comment IN (values)</code>
     */
    public List<com.pingyueryou.ishare.jooq.tables.pojos.IShareComment> fetchByComment(String... values) {
        return fetch(IShareComment.I_SHARE_COMMENT.COMMENT, values);
    }

    /**
     * Fetch records that have <code>created_at IN (values)</code>
     */
    public List<com.pingyueryou.ishare.jooq.tables.pojos.IShareComment> fetchByCreatedAt(Timestamp... values) {
        return fetch(IShareComment.I_SHARE_COMMENT.CREATED_AT, values);
    }

    /**
     * Fetch records that have <code>updated_at IN (values)</code>
     */
    public List<com.pingyueryou.ishare.jooq.tables.pojos.IShareComment> fetchByUpdatedAt(Timestamp... values) {
        return fetch(IShareComment.I_SHARE_COMMENT.UPDATED_AT, values);
    }
}
