/*
 * This file is generated by jOOQ.
*/
package com.pingyueryou.ishare.jooq.tables.daos;


import com.pingyueryou.ishare.jooq.tables.IShareLike;
import com.pingyueryou.ishare.jooq.tables.records.IShareLikeRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IShareLikeDao extends DAOImpl<IShareLikeRecord, com.pingyueryou.ishare.jooq.tables.pojos.IShareLike, Long> {

    /**
     * Create a new IShareLikeDao without any configuration
     */
    public IShareLikeDao() {
        super(IShareLike.I_SHARE_LIKE, com.pingyueryou.ishare.jooq.tables.pojos.IShareLike.class);
    }

    /**
     * Create a new IShareLikeDao with an attached configuration
     */
    public IShareLikeDao(Configuration configuration) {
        super(IShareLike.I_SHARE_LIKE, com.pingyueryou.ishare.jooq.tables.pojos.IShareLike.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(com.pingyueryou.ishare.jooq.tables.pojos.IShareLike object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.pingyueryou.ishare.jooq.tables.pojos.IShareLike> fetchById(Long... values) {
        return fetch(IShareLike.I_SHARE_LIKE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.pingyueryou.ishare.jooq.tables.pojos.IShareLike fetchOneById(Long value) {
        return fetchOne(IShareLike.I_SHARE_LIKE.ID, value);
    }

    /**
     * Fetch records that have <code>share_id IN (values)</code>
     */
    public List<com.pingyueryou.ishare.jooq.tables.pojos.IShareLike> fetchByShareId(Long... values) {
        return fetch(IShareLike.I_SHARE_LIKE.SHARE_ID, values);
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<com.pingyueryou.ishare.jooq.tables.pojos.IShareLike> fetchByUserId(Long... values) {
        return fetch(IShareLike.I_SHARE_LIKE.USER_ID, values);
    }

    /**
     * Fetch records that have <code>created_at IN (values)</code>
     */
    public List<com.pingyueryou.ishare.jooq.tables.pojos.IShareLike> fetchByCreatedAt(Timestamp... values) {
        return fetch(IShareLike.I_SHARE_LIKE.CREATED_AT, values);
    }

    /**
     * Fetch records that have <code>updated_at IN (values)</code>
     */
    public List<com.pingyueryou.ishare.jooq.tables.pojos.IShareLike> fetchByUpdatedAt(Timestamp... values) {
        return fetch(IShareLike.I_SHARE_LIKE.UPDATED_AT, values);
    }
}
