/*
 * This file is generated by jOOQ.
*/
package com.pingyueryou.ishare.jooq.tables.daos;


import com.pingyueryou.ishare.jooq.tables.IShareMedia;
import com.pingyueryou.ishare.jooq.tables.records.IShareMediaRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IShareMediaDao extends DAOImpl<IShareMediaRecord, com.pingyueryou.ishare.jooq.tables.pojos.IShareMedia, Long> {

    /**
     * Create a new IShareMediaDao without any configuration
     */
    public IShareMediaDao() {
        super(IShareMedia.I_SHARE_MEDIA, com.pingyueryou.ishare.jooq.tables.pojos.IShareMedia.class);
    }

    /**
     * Create a new IShareMediaDao with an attached configuration
     */
    public IShareMediaDao(Configuration configuration) {
        super(IShareMedia.I_SHARE_MEDIA, com.pingyueryou.ishare.jooq.tables.pojos.IShareMedia.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(com.pingyueryou.ishare.jooq.tables.pojos.IShareMedia object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.pingyueryou.ishare.jooq.tables.pojos.IShareMedia> fetchById(Long... values) {
        return fetch(IShareMedia.I_SHARE_MEDIA.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.pingyueryou.ishare.jooq.tables.pojos.IShareMedia fetchOneById(Long value) {
        return fetchOne(IShareMedia.I_SHARE_MEDIA.ID, value);
    }

    /**
     * Fetch records that have <code>path IN (values)</code>
     */
    public List<com.pingyueryou.ishare.jooq.tables.pojos.IShareMedia> fetchByPath(String... values) {
        return fetch(IShareMedia.I_SHARE_MEDIA.PATH, values);
    }

    /**
     * Fetch records that have <code>duration IN (values)</code>
     */
    public List<com.pingyueryou.ishare.jooq.tables.pojos.IShareMedia> fetchByDuration(Integer... values) {
        return fetch(IShareMedia.I_SHARE_MEDIA.DURATION, values);
    }

    /**
     * Fetch records that have <code>size IN (values)</code>
     */
    public List<com.pingyueryou.ishare.jooq.tables.pojos.IShareMedia> fetchBySize(Integer... values) {
        return fetch(IShareMedia.I_SHARE_MEDIA.SIZE, values);
    }

    /**
     * Fetch records that have <code>width IN (values)</code>
     */
    public List<com.pingyueryou.ishare.jooq.tables.pojos.IShareMedia> fetchByWidth(Integer... values) {
        return fetch(IShareMedia.I_SHARE_MEDIA.WIDTH, values);
    }

    /**
     * Fetch records that have <code>height IN (values)</code>
     */
    public List<com.pingyueryou.ishare.jooq.tables.pojos.IShareMedia> fetchByHeight(Integer... values) {
        return fetch(IShareMedia.I_SHARE_MEDIA.HEIGHT, values);
    }

    /**
     * Fetch records that have <code>created_at IN (values)</code>
     */
    public List<com.pingyueryou.ishare.jooq.tables.pojos.IShareMedia> fetchByCreatedAt(Timestamp... values) {
        return fetch(IShareMedia.I_SHARE_MEDIA.CREATED_AT, values);
    }

    /**
     * Fetch records that have <code>updated_at IN (values)</code>
     */
    public List<com.pingyueryou.ishare.jooq.tables.pojos.IShareMedia> fetchByUpdatedAt(Timestamp... values) {
        return fetch(IShareMedia.I_SHARE_MEDIA.UPDATED_AT, values);
    }
}
