/*
 * This file is generated by jOOQ.
*/
package com.pingyueryou.ishare.jooq.tables.daos;


import com.pingyueryou.ishare.jooq.tables.IUserClass;
import com.pingyueryou.ishare.jooq.tables.records.IUserClassRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IUserClassDao extends DAOImpl<IUserClassRecord, com.pingyueryou.ishare.jooq.tables.pojos.IUserClass, Long> {

    /**
     * Create a new IUserClassDao without any configuration
     */
    public IUserClassDao() {
        super(IUserClass.I_USER_CLASS, com.pingyueryou.ishare.jooq.tables.pojos.IUserClass.class);
    }

    /**
     * Create a new IUserClassDao with an attached configuration
     */
    public IUserClassDao(Configuration configuration) {
        super(IUserClass.I_USER_CLASS, com.pingyueryou.ishare.jooq.tables.pojos.IUserClass.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(com.pingyueryou.ishare.jooq.tables.pojos.IUserClass object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.pingyueryou.ishare.jooq.tables.pojos.IUserClass> fetchById(Long... values) {
        return fetch(IUserClass.I_USER_CLASS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.pingyueryou.ishare.jooq.tables.pojos.IUserClass fetchOneById(Long value) {
        return fetchOne(IUserClass.I_USER_CLASS.ID, value);
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<com.pingyueryou.ishare.jooq.tables.pojos.IUserClass> fetchByUserId(Long... values) {
        return fetch(IUserClass.I_USER_CLASS.USER_ID, values);
    }

    /**
     * Fetch records that have <code>class_id IN (values)</code>
     */
    public List<com.pingyueryou.ishare.jooq.tables.pojos.IUserClass> fetchByClassId(Long... values) {
        return fetch(IUserClass.I_USER_CLASS.CLASS_ID, values);
    }

    /**
     * Fetch records that have <code>created_at IN (values)</code>
     */
    public List<com.pingyueryou.ishare.jooq.tables.pojos.IUserClass> fetchByCreatedAt(Timestamp... values) {
        return fetch(IUserClass.I_USER_CLASS.CREATED_AT, values);
    }

    /**
     * Fetch records that have <code>updated_at IN (values)</code>
     */
    public List<com.pingyueryou.ishare.jooq.tables.pojos.IUserClass> fetchByUpdatedAt(Timestamp... values) {
        return fetch(IUserClass.I_USER_CLASS.UPDATED_AT, values);
    }
}
