/*
 * This file is generated by jOOQ.
*/
package com.pingyueryou.ishare.jooq.tables.daos;


import com.pingyueryou.ishare.jooq.tables.IUserStudent;
import com.pingyueryou.ishare.jooq.tables.records.IUserStudentRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IUserStudentDao extends DAOImpl<IUserStudentRecord, com.pingyueryou.ishare.jooq.tables.pojos.IUserStudent, Long> {

    /**
     * Create a new IUserStudentDao without any configuration
     */
    public IUserStudentDao() {
        super(IUserStudent.I_USER_STUDENT, com.pingyueryou.ishare.jooq.tables.pojos.IUserStudent.class);
    }

    /**
     * Create a new IUserStudentDao with an attached configuration
     */
    public IUserStudentDao(Configuration configuration) {
        super(IUserStudent.I_USER_STUDENT, com.pingyueryou.ishare.jooq.tables.pojos.IUserStudent.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(com.pingyueryou.ishare.jooq.tables.pojos.IUserStudent object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.pingyueryou.ishare.jooq.tables.pojos.IUserStudent> fetchById(Long... values) {
        return fetch(IUserStudent.I_USER_STUDENT.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.pingyueryou.ishare.jooq.tables.pojos.IUserStudent fetchOneById(Long value) {
        return fetchOne(IUserStudent.I_USER_STUDENT.ID, value);
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<com.pingyueryou.ishare.jooq.tables.pojos.IUserStudent> fetchByUserId(Long... values) {
        return fetch(IUserStudent.I_USER_STUDENT.USER_ID, values);
    }

    /**
     * Fetch records that have <code>student_id IN (values)</code>
     */
    public List<com.pingyueryou.ishare.jooq.tables.pojos.IUserStudent> fetchByStudentId(Long... values) {
        return fetch(IUserStudent.I_USER_STUDENT.STUDENT_ID, values);
    }

    /**
     * Fetch records that have <code>relation IN (values)</code>
     */
    public List<com.pingyueryou.ishare.jooq.tables.pojos.IUserStudent> fetchByRelation(String... values) {
        return fetch(IUserStudent.I_USER_STUDENT.RELATION, values);
    }

    /**
     * Fetch records that have <code>created_at IN (values)</code>
     */
    public List<com.pingyueryou.ishare.jooq.tables.pojos.IUserStudent> fetchByCreatedAt(Timestamp... values) {
        return fetch(IUserStudent.I_USER_STUDENT.CREATED_AT, values);
    }

    /**
     * Fetch records that have <code>updated_at IN (values)</code>
     */
    public List<com.pingyueryou.ishare.jooq.tables.pojos.IUserStudent> fetchByUpdatedAt(Timestamp... values) {
        return fetch(IUserStudent.I_USER_STUDENT.UPDATED_AT, values);
    }
}
