/*
 * This file is generated by jOOQ.
*/
package com.pingyueryou.ishare.jooq.tables.daos;


import com.pingyueryou.ishare.jooq.tables.IUserRole;
import com.pingyueryou.ishare.jooq.tables.records.IUserRoleRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IUserRoleDao extends DAOImpl<IUserRoleRecord, com.pingyueryou.ishare.jooq.tables.pojos.IUserRole, Long> {

    /**
     * Create a new IUserRoleDao without any configuration
     */
    public IUserRoleDao() {
        super(IUserRole.I_USER_ROLE, com.pingyueryou.ishare.jooq.tables.pojos.IUserRole.class);
    }

    /**
     * Create a new IUserRoleDao with an attached configuration
     */
    public IUserRoleDao(Configuration configuration) {
        super(IUserRole.I_USER_ROLE, com.pingyueryou.ishare.jooq.tables.pojos.IUserRole.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(com.pingyueryou.ishare.jooq.tables.pojos.IUserRole object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.pingyueryou.ishare.jooq.tables.pojos.IUserRole> fetchById(Long... values) {
        return fetch(IUserRole.I_USER_ROLE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.pingyueryou.ishare.jooq.tables.pojos.IUserRole fetchOneById(Long value) {
        return fetchOne(IUserRole.I_USER_ROLE.ID, value);
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<com.pingyueryou.ishare.jooq.tables.pojos.IUserRole> fetchByUserId(Long... values) {
        return fetch(IUserRole.I_USER_ROLE.USER_ID, values);
    }

    /**
     * Fetch records that have <code>role IN (values)</code>
     */
    public List<com.pingyueryou.ishare.jooq.tables.pojos.IUserRole> fetchByRole(Integer... values) {
        return fetch(IUserRole.I_USER_ROLE.ROLE, values);
    }

    /**
     * Fetch records that have <code>created_at IN (values)</code>
     */
    public List<com.pingyueryou.ishare.jooq.tables.pojos.IUserRole> fetchByCreatedAt(Timestamp... values) {
        return fetch(IUserRole.I_USER_ROLE.CREATED_AT, values);
    }

    /**
     * Fetch records that have <code>updated_at IN (values)</code>
     */
    public List<com.pingyueryou.ishare.jooq.tables.pojos.IUserRole> fetchByUpdatedAt(Timestamp... values) {
        return fetch(IUserRole.I_USER_ROLE.UPDATED_AT, values);
    }
}
