/*
 * This file is generated by jOOQ.
*/
package com.pingyueryou.ishare.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IClass implements Serializable {

    private static final long serialVersionUID = 1998206136;

    private Long      id;
    private String    name;
    private Long      gradeId;
    private Integer   order;
    private Timestamp createdAt;
    private Timestamp updatedAt;

    public IClass() {}

    public IClass(IClass value) {
        this.id = value.id;
        this.name = value.name;
        this.gradeId = value.gradeId;
        this.order = value.order;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public IClass(
        Long      id,
        String    name,
        Long      gradeId,
        Integer   order,
        Timestamp createdAt,
        Timestamp updatedAt
    ) {
        this.id = id;
        this.name = name;
        this.gradeId = gradeId;
        this.order = order;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Long getGradeId() {
        return this.gradeId;
    }

    public void setGradeId(Long gradeId) {
        this.gradeId = gradeId;
    }

    public Integer getOrder() {
        return this.order;
    }

    public void setOrder(Integer order) {
        this.order = order;
    }

    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    public Timestamp getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(Timestamp updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("IClass (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(gradeId);
        sb.append(", ").append(order);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
