/*
 * This file is generated by jOOQ.
*/
package com.pingyueryou.ishare.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IIndexBanner implements Serializable {

    private static final long serialVersionUID = -1742146305;

    private Long      id;
    private String    imageUrl;
    private Integer   order;
    private Timestamp createdAt;
    private Timestamp updatedAt;

    public IIndexBanner() {}

    public IIndexBanner(IIndexBanner value) {
        this.id = value.id;
        this.imageUrl = value.imageUrl;
        this.order = value.order;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public IIndexBanner(
        Long      id,
        String    imageUrl,
        Integer   order,
        Timestamp createdAt,
        Timestamp updatedAt
    ) {
        this.id = id;
        this.imageUrl = imageUrl;
        this.order = order;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getImageUrl() {
        return this.imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    public Integer getOrder() {
        return this.order;
    }

    public void setOrder(Integer order) {
        this.order = order;
    }

    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    public Timestamp getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(Timestamp updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("IIndexBanner (");

        sb.append(id);
        sb.append(", ").append(imageUrl);
        sb.append(", ").append(order);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
