/*
 * This file is generated by jOOQ.
*/
package com.pingyueryou.ishare.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IItem implements Serializable {

    private static final long serialVersionUID = 1061218246;

    private Long      id;
    private Integer   type;
    private String    title;
    private String    coverUrl;
    private String    desc;
    private Integer   status;
    private Long      uploadUserId;
    private Long      classId;
    private Timestamp createdAt;
    private Timestamp updatedAt;

    public IItem() {}

    public IItem(IItem value) {
        this.id = value.id;
        this.type = value.type;
        this.title = value.title;
        this.coverUrl = value.coverUrl;
        this.desc = value.desc;
        this.status = value.status;
        this.uploadUserId = value.uploadUserId;
        this.classId = value.classId;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public IItem(
        Long      id,
        Integer   type,
        String    title,
        String    coverUrl,
        String    desc,
        Integer   status,
        Long      uploadUserId,
        Long      classId,
        Timestamp createdAt,
        Timestamp updatedAt
    ) {
        this.id = id;
        this.type = type;
        this.title = title;
        this.coverUrl = coverUrl;
        this.desc = desc;
        this.status = status;
        this.uploadUserId = uploadUserId;
        this.classId = classId;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getType() {
        return this.type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getCoverUrl() {
        return this.coverUrl;
    }

    public void setCoverUrl(String coverUrl) {
        this.coverUrl = coverUrl;
    }

    public String getDesc() {
        return this.desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }

    public Integer getStatus() {
        return this.status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Long getUploadUserId() {
        return this.uploadUserId;
    }

    public void setUploadUserId(Long uploadUserId) {
        this.uploadUserId = uploadUserId;
    }

    public Long getClassId() {
        return this.classId;
    }

    public void setClassId(Long classId) {
        this.classId = classId;
    }

    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    public Timestamp getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(Timestamp updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("IItem (");

        sb.append(id);
        sb.append(", ").append(type);
        sb.append(", ").append(title);
        sb.append(", ").append(coverUrl);
        sb.append(", ").append(desc);
        sb.append(", ").append(status);
        sb.append(", ").append(uploadUserId);
        sb.append(", ").append(classId);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
