/*
 * This file is generated by jOOQ.
*/
package com.pingyueryou.ishare.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IShare implements Serializable {

    private static final long serialVersionUID = 1395014127;

    private Long      id;
    private String    title;
    private String    mediaUrl;
    private Integer   mediaType;
    private Long      uploadUserId;
    private Long      classId;
    private Long      itemId;
    private String    desc;
    private Timestamp createdAt;
    private Timestamp updatedAt;

    public IShare() {}

    public IShare(IShare value) {
        this.id = value.id;
        this.title = value.title;
        this.mediaUrl = value.mediaUrl;
        this.mediaType = value.mediaType;
        this.uploadUserId = value.uploadUserId;
        this.classId = value.classId;
        this.itemId = value.itemId;
        this.desc = value.desc;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public IShare(
        Long      id,
        String    title,
        String    mediaUrl,
        Integer   mediaType,
        Long      uploadUserId,
        Long      classId,
        Long      itemId,
        String    desc,
        Timestamp createdAt,
        Timestamp updatedAt
    ) {
        this.id = id;
        this.title = title;
        this.mediaUrl = mediaUrl;
        this.mediaType = mediaType;
        this.uploadUserId = uploadUserId;
        this.classId = classId;
        this.itemId = itemId;
        this.desc = desc;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getMediaUrl() {
        return this.mediaUrl;
    }

    public void setMediaUrl(String mediaUrl) {
        this.mediaUrl = mediaUrl;
    }

    public Integer getMediaType() {
        return this.mediaType;
    }

    public void setMediaType(Integer mediaType) {
        this.mediaType = mediaType;
    }

    public Long getUploadUserId() {
        return this.uploadUserId;
    }

    public void setUploadUserId(Long uploadUserId) {
        this.uploadUserId = uploadUserId;
    }

    public Long getClassId() {
        return this.classId;
    }

    public void setClassId(Long classId) {
        this.classId = classId;
    }

    public Long getItemId() {
        return this.itemId;
    }

    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    public String getDesc() {
        return this.desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }

    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    public Timestamp getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(Timestamp updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("IShare (");

        sb.append(id);
        sb.append(", ").append(title);
        sb.append(", ").append(mediaUrl);
        sb.append(", ").append(mediaType);
        sb.append(", ").append(uploadUserId);
        sb.append(", ").append(classId);
        sb.append(", ").append(itemId);
        sb.append(", ").append(desc);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
