/*
 * This file is generated by jOOQ.
*/
package com.pingyueryou.ishare.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IShareLike implements Serializable {

    private static final long serialVersionUID = -414463925;

    private Long      id;
    private Long      shareId;
    private Long      userId;
    private Timestamp createdAt;
    private Timestamp updatedAt;

    public IShareLike() {}

    public IShareLike(IShareLike value) {
        this.id = value.id;
        this.shareId = value.shareId;
        this.userId = value.userId;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public IShareLike(
        Long      id,
        Long      shareId,
        Long      userId,
        Timestamp createdAt,
        Timestamp updatedAt
    ) {
        this.id = id;
        this.shareId = shareId;
        this.userId = userId;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getShareId() {
        return this.shareId;
    }

    public void setShareId(Long shareId) {
        this.shareId = shareId;
    }

    public Long getUserId() {
        return this.userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    public Timestamp getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(Timestamp updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("IShareLike (");

        sb.append(id);
        sb.append(", ").append(shareId);
        sb.append(", ").append(userId);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
