/*
 * This file is generated by jOOQ.
*/
package com.pingyueryou.ishare.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IShare implements Serializable {

    private static final long serialVersionUID = 1651259166;

    private Long      id;
    private String    title;
    private Long      mediaId;
    private Long      uploadUserId;
    private Long      itemId;
    private Long      studentId;
    private String    desc;
    private Timestamp createdAt;
    private Timestamp updatedAt;

    public IShare() {}

    public IShare(IShare value) {
        this.id = value.id;
        this.title = value.title;
        this.mediaId = value.mediaId;
        this.uploadUserId = value.uploadUserId;
        this.itemId = value.itemId;
        this.studentId = value.studentId;
        this.desc = value.desc;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public IShare(
        Long      id,
        String    title,
        Long      mediaId,
        Long      uploadUserId,
        Long      itemId,
        Long      studentId,
        String    desc,
        Timestamp createdAt,
        Timestamp updatedAt
    ) {
        this.id = id;
        this.title = title;
        this.mediaId = mediaId;
        this.uploadUserId = uploadUserId;
        this.itemId = itemId;
        this.studentId = studentId;
        this.desc = desc;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Long getMediaId() {
        return this.mediaId;
    }

    public void setMediaId(Long mediaId) {
        this.mediaId = mediaId;
    }

    public Long getUploadUserId() {
        return this.uploadUserId;
    }

    public void setUploadUserId(Long uploadUserId) {
        this.uploadUserId = uploadUserId;
    }

    public Long getItemId() {
        return this.itemId;
    }

    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    public Long getStudentId() {
        return this.studentId;
    }

    public void setStudentId(Long studentId) {
        this.studentId = studentId;
    }

    public String getDesc() {
        return this.desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }

    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    public Timestamp getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(Timestamp updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("IShare (");

        sb.append(id);
        sb.append(", ").append(title);
        sb.append(", ").append(mediaId);
        sb.append(", ").append(uploadUserId);
        sb.append(", ").append(itemId);
        sb.append(", ").append(studentId);
        sb.append(", ").append(desc);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
