/*
 * This file is generated by jOOQ.
*/
package com.pingyueryou.ishare.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IUserStudent implements Serializable {

    private static final long serialVersionUID = -1809090465;

    private Long      id;
    private Long      userId;
    private Long      studentId;
    private String    relation;
    private Timestamp createdAt;
    private Timestamp updatedAt;

    public IUserStudent() {}

    public IUserStudent(IUserStudent value) {
        this.id = value.id;
        this.userId = value.userId;
        this.studentId = value.studentId;
        this.relation = value.relation;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public IUserStudent(
        Long      id,
        Long      userId,
        Long      studentId,
        String    relation,
        Timestamp createdAt,
        Timestamp updatedAt
    ) {
        this.id = id;
        this.userId = userId;
        this.studentId = studentId;
        this.relation = relation;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getUserId() {
        return this.userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Long getStudentId() {
        return this.studentId;
    }

    public void setStudentId(Long studentId) {
        this.studentId = studentId;
    }

    public String getRelation() {
        return this.relation;
    }

    public void setRelation(String relation) {
        this.relation = relation;
    }

    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    public Timestamp getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(Timestamp updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("IUserStudent (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(studentId);
        sb.append(", ").append(relation);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
