/*
 * This file is generated by jOOQ.
*/
package com.pingyueryou.ishare.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IUser implements Serializable {

    private static final long serialVersionUID = 133766644;

    private Long      id;
    private String    nickName;
    private Integer   gender;
    private Timestamp birthday;
    private String    openId;
    private String    unionId;
    private String    avatarUrl;
    private Timestamp createdAt;
    private Timestamp updatedAt;

    public IUser() {}

    public IUser(IUser value) {
        this.id = value.id;
        this.nickName = value.nickName;
        this.gender = value.gender;
        this.birthday = value.birthday;
        this.openId = value.openId;
        this.unionId = value.unionId;
        this.avatarUrl = value.avatarUrl;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public IUser(
        Long      id,
        String    nickName,
        Integer   gender,
        Timestamp birthday,
        String    openId,
        String    unionId,
        String    avatarUrl,
        Timestamp createdAt,
        Timestamp updatedAt
    ) {
        this.id = id;
        this.nickName = nickName;
        this.gender = gender;
        this.birthday = birthday;
        this.openId = openId;
        this.unionId = unionId;
        this.avatarUrl = avatarUrl;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNickName() {
        return this.nickName;
    }

    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    public Integer getGender() {
        return this.gender;
    }

    public void setGender(Integer gender) {
        this.gender = gender;
    }

    public Timestamp getBirthday() {
        return this.birthday;
    }

    public void setBirthday(Timestamp birthday) {
        this.birthday = birthday;
    }

    public String getOpenId() {
        return this.openId;
    }

    public void setOpenId(String openId) {
        this.openId = openId;
    }

    public String getUnionId() {
        return this.unionId;
    }

    public void setUnionId(String unionId) {
        this.unionId = unionId;
    }

    public String getAvatarUrl() {
        return this.avatarUrl;
    }

    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl;
    }

    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    public Timestamp getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(Timestamp updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("IUser (");

        sb.append(id);
        sb.append(", ").append(nickName);
        sb.append(", ").append(gender);
        sb.append(", ").append(birthday);
        sb.append(", ").append(openId);
        sb.append(", ").append(unionId);
        sb.append(", ").append(avatarUrl);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
