/*
 * This file is generated by jOOQ.
*/
package com.pingyueryou.ishare.jooq;


import com.pingyueryou.ishare.jooq.tables.IUser;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>ishare</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index I_USER_PRIMARY = Indexes0.I_USER_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index I_USER_PRIMARY = Internal.createIndex("PRIMARY", IUser.I_USER, new OrderField[] { IUser.I_USER.ID }, true);
    }
}
