/*
 * This file is generated by jOOQ.
*/
package com.pingyueryou.ishare.jooq;


import com.pingyueryou.ishare.jooq.tables.IUser;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Ishare extends SchemaImpl {

    private static final long serialVersionUID = 878028344;

    /**
     * The reference instance of <code>ishare</code>
     */
    public static final Ishare ISHARE = new Ishare();

    /**
     * The table <code>ishare.i_user</code>.
     */
    public final IUser I_USER = com.pingyueryou.ishare.jooq.tables.IUser.I_USER;

    /**
     * No further instances allowed
     */
    private Ishare() {
        super("ishare", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            IUser.I_USER);
    }
}
