/*
 * This file is generated by jOOQ.
*/
package com.pingyueryou.ishare.jooq;


import com.pingyueryou.ishare.jooq.tables.IClass;
import com.pingyueryou.ishare.jooq.tables.IGrade;
import com.pingyueryou.ishare.jooq.tables.IIdAuthOrder;
import com.pingyueryou.ishare.jooq.tables.IItem;
import com.pingyueryou.ishare.jooq.tables.IItemLendOrder;
import com.pingyueryou.ishare.jooq.tables.IItemTag;
import com.pingyueryou.ishare.jooq.tables.IItemTagItem;
import com.pingyueryou.ishare.jooq.tables.IShare;
import com.pingyueryou.ishare.jooq.tables.IShareComment;
import com.pingyueryou.ishare.jooq.tables.IShareLike;
import com.pingyueryou.ishare.jooq.tables.IShareMedia;
import com.pingyueryou.ishare.jooq.tables.IStudent;
import com.pingyueryou.ishare.jooq.tables.IUser;
import com.pingyueryou.ishare.jooq.tables.IUserClass;
import com.pingyueryou.ishare.jooq.tables.IUserRole;
import com.pingyueryou.ishare.jooq.tables.IUserStudent;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Ishare extends SchemaImpl {

    private static final long serialVersionUID = -1508119091;

    /**
     * The reference instance of <code>ishare</code>
     */
    public static final Ishare ISHARE = new Ishare();

    /**
     * The table <code>ishare.i_class</code>.
     */
    public final IClass I_CLASS = com.pingyueryou.ishare.jooq.tables.IClass.I_CLASS;

    /**
     * The table <code>ishare.i_grade</code>.
     */
    public final IGrade I_GRADE = com.pingyueryou.ishare.jooq.tables.IGrade.I_GRADE;

    /**
     * The table <code>ishare.i_id_auth_order</code>.
     */
    public final IIdAuthOrder I_ID_AUTH_ORDER = com.pingyueryou.ishare.jooq.tables.IIdAuthOrder.I_ID_AUTH_ORDER;

    /**
     * The table <code>ishare.i_item</code>.
     */
    public final IItem I_ITEM = com.pingyueryou.ishare.jooq.tables.IItem.I_ITEM;

    /**
     * The table <code>ishare.i_item_lend_order</code>.
     */
    public final IItemLendOrder I_ITEM_LEND_ORDER = com.pingyueryou.ishare.jooq.tables.IItemLendOrder.I_ITEM_LEND_ORDER;

    /**
     * The table <code>ishare.i_item_tag</code>.
     */
    public final IItemTag I_ITEM_TAG = com.pingyueryou.ishare.jooq.tables.IItemTag.I_ITEM_TAG;

    /**
     * The table <code>ishare.i_item_tag_item</code>.
     */
    public final IItemTagItem I_ITEM_TAG_ITEM = com.pingyueryou.ishare.jooq.tables.IItemTagItem.I_ITEM_TAG_ITEM;

    /**
     * The table <code>ishare.i_share</code>.
     */
    public final IShare I_SHARE = com.pingyueryou.ishare.jooq.tables.IShare.I_SHARE;

    /**
     * The table <code>ishare.i_share_comment</code>.
     */
    public final IShareComment I_SHARE_COMMENT = com.pingyueryou.ishare.jooq.tables.IShareComment.I_SHARE_COMMENT;

    /**
     * The table <code>ishare.i_share_like</code>.
     */
    public final IShareLike I_SHARE_LIKE = com.pingyueryou.ishare.jooq.tables.IShareLike.I_SHARE_LIKE;

    /**
     * The table <code>ishare.i_share_media</code>.
     */
    public final IShareMedia I_SHARE_MEDIA = com.pingyueryou.ishare.jooq.tables.IShareMedia.I_SHARE_MEDIA;

    /**
     * The table <code>ishare.i_student</code>.
     */
    public final IStudent I_STUDENT = com.pingyueryou.ishare.jooq.tables.IStudent.I_STUDENT;

    /**
     * The table <code>ishare.i_user</code>.
     */
    public final IUser I_USER = com.pingyueryou.ishare.jooq.tables.IUser.I_USER;

    /**
     * The table <code>ishare.i_user_class</code>.
     */
    public final IUserClass I_USER_CLASS = com.pingyueryou.ishare.jooq.tables.IUserClass.I_USER_CLASS;

    /**
     * The table <code>ishare.i_user_role</code>.
     */
    public final IUserRole I_USER_ROLE = com.pingyueryou.ishare.jooq.tables.IUserRole.I_USER_ROLE;

    /**
     * The table <code>ishare.i_user_student</code>.
     */
    public final IUserStudent I_USER_STUDENT = com.pingyueryou.ishare.jooq.tables.IUserStudent.I_USER_STUDENT;

    /**
     * No further instances allowed
     */
    private Ishare() {
        super("ishare", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            IClass.I_CLASS,
            IGrade.I_GRADE,
            IIdAuthOrder.I_ID_AUTH_ORDER,
            IItem.I_ITEM,
            IItemLendOrder.I_ITEM_LEND_ORDER,
            IItemTag.I_ITEM_TAG,
            IItemTagItem.I_ITEM_TAG_ITEM,
            IShare.I_SHARE,
            IShareComment.I_SHARE_COMMENT,
            IShareLike.I_SHARE_LIKE,
            IShareMedia.I_SHARE_MEDIA,
            IStudent.I_STUDENT,
            IUser.I_USER,
            IUserClass.I_USER_CLASS,
            IUserRole.I_USER_ROLE,
            IUserStudent.I_USER_STUDENT);
    }
}
