/*
 * This file is generated by jOOQ.
*/
package com.pingyueryou.ishare.jooq;


import com.pingyueryou.ishare.jooq.tables.IUser;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in ishare
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>ishare.i_user</code>.
     */
    public static final IUser I_USER = com.pingyueryou.ishare.jooq.tables.IUser.I_USER;
}
