/*
 * This file is generated by jOOQ.
*/
package com.pingyueryou.ishare.jooq.tables.records;


import com.pingyueryou.ishare.jooq.tables.IIdAuthOrder;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IIdAuthOrderRecord extends UpdatableRecordImpl<IIdAuthOrderRecord> implements Record9<Long, Long, Integer, Long, String, String, Integer, Timestamp, Timestamp> {

    private static final long serialVersionUID = 2037790688;

    /**
     * Setter for <code>ishare.i_id_auth_order.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>ishare.i_id_auth_order.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>ishare.i_id_auth_order.user_id</code>.
     */
    public void setUserId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>ishare.i_id_auth_order.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>ishare.i_id_auth_order.role</code>.
     */
    public void setRole(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>ishare.i_id_auth_order.role</code>.
     */
    public Integer getRole() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>ishare.i_id_auth_order.class_id</code>.
     */
    public void setClassId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>ishare.i_id_auth_order.class_id</code>.
     */
    public Long getClassId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>ishare.i_id_auth_order.student_name</code>.
     */
    public void setStudentName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>ishare.i_id_auth_order.student_name</code>.
     */
    public String getStudentName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>ishare.i_id_auth_order.relation</code>.
     */
    public void setRelation(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>ishare.i_id_auth_order.relation</code>.
     */
    public String getRelation() {
        return (String) get(5);
    }

    /**
     * Setter for <code>ishare.i_id_auth_order.status</code>.
     */
    public void setStatus(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>ishare.i_id_auth_order.status</code>.
     */
    public Integer getStatus() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>ishare.i_id_auth_order.created_at</code>.
     */
    public void setCreatedAt(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>ishare.i_id_auth_order.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>ishare.i_id_auth_order.updated_at</code>.
     */
    public void setUpdatedAt(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>ishare.i_id_auth_order.updated_at</code>.
     */
    public Timestamp getUpdatedAt() {
        return (Timestamp) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, Long, Integer, Long, String, String, Integer, Timestamp, Timestamp> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, Long, Integer, Long, String, String, Integer, Timestamp, Timestamp> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return IIdAuthOrder.I_ID_AUTH_ORDER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return IIdAuthOrder.I_ID_AUTH_ORDER.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return IIdAuthOrder.I_ID_AUTH_ORDER.ROLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return IIdAuthOrder.I_ID_AUTH_ORDER.CLASS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return IIdAuthOrder.I_ID_AUTH_ORDER.STUDENT_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return IIdAuthOrder.I_ID_AUTH_ORDER.RELATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return IIdAuthOrder.I_ID_AUTH_ORDER.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return IIdAuthOrder.I_ID_AUTH_ORDER.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return IIdAuthOrder.I_ID_AUTH_ORDER.UPDATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getRole();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component4() {
        return getClassId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getStudentName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getRelation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getRole();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getClassId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getStudentName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getRelation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IIdAuthOrderRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IIdAuthOrderRecord value2(Long value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IIdAuthOrderRecord value3(Integer value) {
        setRole(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IIdAuthOrderRecord value4(Long value) {
        setClassId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IIdAuthOrderRecord value5(String value) {
        setStudentName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IIdAuthOrderRecord value6(String value) {
        setRelation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IIdAuthOrderRecord value7(Integer value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IIdAuthOrderRecord value8(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IIdAuthOrderRecord value9(Timestamp value) {
        setUpdatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IIdAuthOrderRecord values(Long value1, Long value2, Integer value3, Long value4, String value5, String value6, Integer value7, Timestamp value8, Timestamp value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached IIdAuthOrderRecord
     */
    public IIdAuthOrderRecord() {
        super(IIdAuthOrder.I_ID_AUTH_ORDER);
    }

    /**
     * Create a detached, initialised IIdAuthOrderRecord
     */
    public IIdAuthOrderRecord(Long id, Long userId, Integer role, Long classId, String studentName, String relation, Integer status, Timestamp createdAt, Timestamp updatedAt) {
        super(IIdAuthOrder.I_ID_AUTH_ORDER);

        set(0, id);
        set(1, userId);
        set(2, role);
        set(3, classId);
        set(4, studentName);
        set(5, relation);
        set(6, status);
        set(7, createdAt);
        set(8, updatedAt);
    }
}
