/*
 * This file is generated by jOOQ.
*/
package com.pingyueryou.ishare.jooq.tables.records;


import com.pingyueryou.ishare.jooq.tables.IItem;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IItemRecord extends UpdatableRecordImpl<IItemRecord> implements Record10<Long, Integer, String, String, String, Integer, Long, Long, Timestamp, Timestamp> {

    private static final long serialVersionUID = 32061678;

    /**
     * Setter for <code>ishare.i_item.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>ishare.i_item.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>ishare.i_item.type</code>.
     */
    public void setType(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>ishare.i_item.type</code>.
     */
    public Integer getType() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>ishare.i_item.title</code>.
     */
    public void setTitle(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>ishare.i_item.title</code>.
     */
    public String getTitle() {
        return (String) get(2);
    }

    /**
     * Setter for <code>ishare.i_item.cover_url</code>.
     */
    public void setCoverUrl(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>ishare.i_item.cover_url</code>.
     */
    public String getCoverUrl() {
        return (String) get(3);
    }

    /**
     * Setter for <code>ishare.i_item.desc</code>.
     */
    public void setDesc(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>ishare.i_item.desc</code>.
     */
    public String getDesc() {
        return (String) get(4);
    }

    /**
     * Setter for <code>ishare.i_item.status</code>.
     */
    public void setStatus(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>ishare.i_item.status</code>.
     */
    public Integer getStatus() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>ishare.i_item.upload_user_id</code>.
     */
    public void setUploadUserId(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>ishare.i_item.upload_user_id</code>.
     */
    public Long getUploadUserId() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>ishare.i_item.class_id</code>.
     */
    public void setClassId(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>ishare.i_item.class_id</code>.
     */
    public Long getClassId() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>ishare.i_item.created_at</code>.
     */
    public void setCreatedAt(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>ishare.i_item.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(8);
    }

    /**
     * Setter for <code>ishare.i_item.updated_at</code>.
     */
    public void setUpdatedAt(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>ishare.i_item.updated_at</code>.
     */
    public Timestamp getUpdatedAt() {
        return (Timestamp) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Long, Integer, String, String, String, Integer, Long, Long, Timestamp, Timestamp> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Long, Integer, String, String, String, Integer, Long, Long, Timestamp, Timestamp> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return IItem.I_ITEM.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return IItem.I_ITEM.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return IItem.I_ITEM.TITLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return IItem.I_ITEM.COVER_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return IItem.I_ITEM.DESC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return IItem.I_ITEM.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field7() {
        return IItem.I_ITEM.UPLOAD_USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field8() {
        return IItem.I_ITEM.CLASS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return IItem.I_ITEM.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return IItem.I_ITEM.UPDATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getCoverUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getDesc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component7() {
        return getUploadUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component8() {
        return getClassId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component10() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getCoverUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getDesc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value7() {
        return getUploadUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value8() {
        return getClassId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IItemRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IItemRecord value2(Integer value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IItemRecord value3(String value) {
        setTitle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IItemRecord value4(String value) {
        setCoverUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IItemRecord value5(String value) {
        setDesc(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IItemRecord value6(Integer value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IItemRecord value7(Long value) {
        setUploadUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IItemRecord value8(Long value) {
        setClassId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IItemRecord value9(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IItemRecord value10(Timestamp value) {
        setUpdatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IItemRecord values(Long value1, Integer value2, String value3, String value4, String value5, Integer value6, Long value7, Long value8, Timestamp value9, Timestamp value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached IItemRecord
     */
    public IItemRecord() {
        super(IItem.I_ITEM);
    }

    /**
     * Create a detached, initialised IItemRecord
     */
    public IItemRecord(Long id, Integer type, String title, String coverUrl, String desc, Integer status, Long uploadUserId, Long classId, Timestamp createdAt, Timestamp updatedAt) {
        super(IItem.I_ITEM);

        set(0, id);
        set(1, type);
        set(2, title);
        set(3, coverUrl);
        set(4, desc);
        set(5, status);
        set(6, uploadUserId);
        set(7, classId);
        set(8, createdAt);
        set(9, updatedAt);
    }
}
