/*
 * This file is generated by jOOQ.
*/
package com.pingyueryou.ishare.jooq.tables.records;


import com.pingyueryou.ishare.jooq.tables.IItemTagItem;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IItemTagItemRecord extends UpdatableRecordImpl<IItemTagItemRecord> implements Record5<Long, Long, Long, Timestamp, Timestamp> {

    private static final long serialVersionUID = 230439846;

    /**
     * Setter for <code>ishare.i_item_tag_item.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>ishare.i_item_tag_item.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>ishare.i_item_tag_item.item_id</code>.
     */
    public void setItemId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>ishare.i_item_tag_item.item_id</code>.
     */
    public Long getItemId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>ishare.i_item_tag_item.tag_id</code>.
     */
    public void setTagId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>ishare.i_item_tag_item.tag_id</code>.
     */
    public Long getTagId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>ishare.i_item_tag_item.created_at</code>.
     */
    public void setCreatedAt(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>ishare.i_item_tag_item.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>ishare.i_item_tag_item.updated_at</code>.
     */
    public void setUpdatedAt(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>ishare.i_item_tag_item.updated_at</code>.
     */
    public Timestamp getUpdatedAt() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, Long, Long, Timestamp, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, Long, Long, Timestamp, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return IItemTagItem.I_ITEM_TAG_ITEM.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return IItemTagItem.I_ITEM_TAG_ITEM.ITEM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return IItemTagItem.I_ITEM_TAG_ITEM.TAG_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return IItemTagItem.I_ITEM_TAG_ITEM.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return IItemTagItem.I_ITEM_TAG_ITEM.UPDATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getItemId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getTagId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getItemId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getTagId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IItemTagItemRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IItemTagItemRecord value2(Long value) {
        setItemId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IItemTagItemRecord value3(Long value) {
        setTagId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IItemTagItemRecord value4(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IItemTagItemRecord value5(Timestamp value) {
        setUpdatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IItemTagItemRecord values(Long value1, Long value2, Long value3, Timestamp value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached IItemTagItemRecord
     */
    public IItemTagItemRecord() {
        super(IItemTagItem.I_ITEM_TAG_ITEM);
    }

    /**
     * Create a detached, initialised IItemTagItemRecord
     */
    public IItemTagItemRecord(Long id, Long itemId, Long tagId, Timestamp createdAt, Timestamp updatedAt) {
        super(IItemTagItem.I_ITEM_TAG_ITEM);

        set(0, id);
        set(1, itemId);
        set(2, tagId);
        set(3, createdAt);
        set(4, updatedAt);
    }
}
