/*
 * This file is generated by jOOQ.
*/
package com.pingyueryou.ishare.jooq.tables.records;


import com.pingyueryou.ishare.jooq.tables.IItemLendOrder;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IItemLendOrderRecord extends UpdatableRecordImpl<IItemLendOrderRecord> implements Record8<Long, Long, Long, Long, Long, Integer, Timestamp, Timestamp> {

    private static final long serialVersionUID = 1903578239;

    /**
     * Setter for <code>ishare.i_item_lend_order.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>ishare.i_item_lend_order.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>ishare.i_item_lend_order.user_id</code>.
     */
    public void setUserId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>ishare.i_item_lend_order.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>ishare.i_item_lend_order.item_id</code>.
     */
    public void setItemId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>ishare.i_item_lend_order.item_id</code>.
     */
    public Long getItemId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>ishare.i_item_lend_order.class_id</code>.
     */
    public void setClassId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>ishare.i_item_lend_order.class_id</code>.
     */
    public Long getClassId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>ishare.i_item_lend_order.student_id</code>.
     */
    public void setStudentId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>ishare.i_item_lend_order.student_id</code>.
     */
    public Long getStudentId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>ishare.i_item_lend_order.status</code>.
     */
    public void setStatus(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>ishare.i_item_lend_order.status</code>.
     */
    public Integer getStatus() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>ishare.i_item_lend_order.created_at</code>.
     */
    public void setCreatedAt(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>ishare.i_item_lend_order.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>ishare.i_item_lend_order.updated_at</code>.
     */
    public void setUpdatedAt(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>ishare.i_item_lend_order.updated_at</code>.
     */
    public Timestamp getUpdatedAt() {
        return (Timestamp) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, Long, Long, Long, Long, Integer, Timestamp, Timestamp> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, Long, Long, Long, Long, Integer, Timestamp, Timestamp> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return IItemLendOrder.I_ITEM_LEND_ORDER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return IItemLendOrder.I_ITEM_LEND_ORDER.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return IItemLendOrder.I_ITEM_LEND_ORDER.ITEM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return IItemLendOrder.I_ITEM_LEND_ORDER.CLASS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return IItemLendOrder.I_ITEM_LEND_ORDER.STUDENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return IItemLendOrder.I_ITEM_LEND_ORDER.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return IItemLendOrder.I_ITEM_LEND_ORDER.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return IItemLendOrder.I_ITEM_LEND_ORDER.UPDATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getItemId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component4() {
        return getClassId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component5() {
        return getStudentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getItemId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getClassId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getStudentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IItemLendOrderRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IItemLendOrderRecord value2(Long value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IItemLendOrderRecord value3(Long value) {
        setItemId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IItemLendOrderRecord value4(Long value) {
        setClassId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IItemLendOrderRecord value5(Long value) {
        setStudentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IItemLendOrderRecord value6(Integer value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IItemLendOrderRecord value7(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IItemLendOrderRecord value8(Timestamp value) {
        setUpdatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IItemLendOrderRecord values(Long value1, Long value2, Long value3, Long value4, Long value5, Integer value6, Timestamp value7, Timestamp value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached IItemLendOrderRecord
     */
    public IItemLendOrderRecord() {
        super(IItemLendOrder.I_ITEM_LEND_ORDER);
    }

    /**
     * Create a detached, initialised IItemLendOrderRecord
     */
    public IItemLendOrderRecord(Long id, Long userId, Long itemId, Long classId, Long studentId, Integer status, Timestamp createdAt, Timestamp updatedAt) {
        super(IItemLendOrder.I_ITEM_LEND_ORDER);

        set(0, id);
        set(1, userId);
        set(2, itemId);
        set(3, classId);
        set(4, studentId);
        set(5, status);
        set(6, createdAt);
        set(7, updatedAt);
    }
}
