/*
 * This file is generated by jOOQ.
*/
package com.pingyueryou.ishare.jooq.tables.records;


import com.pingyueryou.ishare.jooq.tables.IShare;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IShareRecord extends UpdatableRecordImpl<IShareRecord> implements Record9<Long, String, Long, Long, Long, Long, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = 1971365960;

    /**
     * Setter for <code>ishare.i_share.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>ishare.i_share.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>ishare.i_share.title</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>ishare.i_share.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>ishare.i_share.media_id</code>.
     */
    public void setMediaId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>ishare.i_share.media_id</code>.
     */
    public Long getMediaId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>ishare.i_share.upload_user_id</code>.
     */
    public void setUploadUserId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>ishare.i_share.upload_user_id</code>.
     */
    public Long getUploadUserId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>ishare.i_share.item_id</code>.
     */
    public void setItemId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>ishare.i_share.item_id</code>.
     */
    public Long getItemId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>ishare.i_share.student_id</code>.
     */
    public void setStudentId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>ishare.i_share.student_id</code>.
     */
    public Long getStudentId() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>ishare.i_share.desc</code>.
     */
    public void setDesc(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>ishare.i_share.desc</code>.
     */
    public String getDesc() {
        return (String) get(6);
    }

    /**
     * Setter for <code>ishare.i_share.created_at</code>.
     */
    public void setCreatedAt(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>ishare.i_share.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>ishare.i_share.updated_at</code>.
     */
    public void setUpdatedAt(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>ishare.i_share.updated_at</code>.
     */
    public Timestamp getUpdatedAt() {
        return (Timestamp) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, String, Long, Long, Long, Long, String, Timestamp, Timestamp> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, String, Long, Long, Long, Long, String, Timestamp, Timestamp> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return IShare.I_SHARE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return IShare.I_SHARE.TITLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return IShare.I_SHARE.MEDIA_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return IShare.I_SHARE.UPLOAD_USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return IShare.I_SHARE.ITEM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field6() {
        return IShare.I_SHARE.STUDENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return IShare.I_SHARE.DESC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return IShare.I_SHARE.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return IShare.I_SHARE.UPDATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getMediaId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component4() {
        return getUploadUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component5() {
        return getItemId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component6() {
        return getStudentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getDesc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getMediaId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getUploadUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getItemId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value6() {
        return getStudentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getDesc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IShareRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IShareRecord value2(String value) {
        setTitle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IShareRecord value3(Long value) {
        setMediaId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IShareRecord value4(Long value) {
        setUploadUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IShareRecord value5(Long value) {
        setItemId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IShareRecord value6(Long value) {
        setStudentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IShareRecord value7(String value) {
        setDesc(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IShareRecord value8(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IShareRecord value9(Timestamp value) {
        setUpdatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IShareRecord values(Long value1, String value2, Long value3, Long value4, Long value5, Long value6, String value7, Timestamp value8, Timestamp value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached IShareRecord
     */
    public IShareRecord() {
        super(IShare.I_SHARE);
    }

    /**
     * Create a detached, initialised IShareRecord
     */
    public IShareRecord(Long id, String title, Long mediaId, Long uploadUserId, Long itemId, Long studentId, String desc, Timestamp createdAt, Timestamp updatedAt) {
        super(IShare.I_SHARE);

        set(0, id);
        set(1, title);
        set(2, mediaId);
        set(3, uploadUserId);
        set(4, itemId);
        set(5, studentId);
        set(6, desc);
        set(7, createdAt);
        set(8, updatedAt);
    }
}
